<?php

/* 

Custom module for vanilla integration
This also requires orchid module (custom)
Install vanilla to /discussions/ and use embed to host discussion on /discuss page
Install steps:

Install Vanilla
- Create /discussions folder in Drupal root
- Clone vanilla "git clone https://github.com/vanilla/vanilla discussions"
- Create mysql database for vanilla, etc.
- Download http://vanillaforums.org/addon/jsconnect-plugin
- Download http://vanillaforums.org/addon/jsconnectautosignin-plugin
- Visit /discussions in web browser and install vanilla
- Setup jsconnect plugin (set Authenticate URL to /orchid/jsconnect)
- In jsconnect plugin set "This is trusted connection and can sync roles & permissions."
- In jsconnect plugin set "Make this connection your default signin method."
- Add roles for chapter leader, non-validated, moderator, approved user, administrator (to sync)
- Set embed
- $Configuration['Garden']['Profile']['EditPhotos'] = FALSE;
- $Configuration['Garden']['UserAccount']['AllowEdit'] = FALSE;
- $Configuration['Garden']['Profile']['ShowActivities'] = FALSE;

Drupal
- Enable drupal modules: "drush en orchid tm_discuss"
- Go to /admin/config/vanilla/orchid to configure
- Set client id, secret key from vanilla setttings
- Set Vanilla forum URL to /discussions/
- Enable avatar sync

Additional references: 
- Orchid module - https://www.drupal.org/project/orchid
- Orchid instructions - https://www.drupal.org/node/1117992

*/

// hide the discuss menu if configured to to so
function tm_discuss_init() {
	global $conf;

	// hide for logged in user
	if (isset($conf["tm_discuss_menu_hide"])) {
		if ($conf["tm_discuss_menu_hide"]) {

			// check cookie
			$css_class = $conf["tm_discuss_menu_class"];
			if (!isset($_COOKIE['Drupal_visitor_show_discuss_menu'])) {
				drupal_add_css('.' . $css_class . ' { display: none; }', 'inline');
			}
		}
	}
}


// Update meta tags for /discuss page
function tm_discuss_metatag_metatags_view_alter(&$output, $instance) {

	global $conf;

	$discuss_menu_path = "discuss"; // default
	if (isset($conf["tm_discuss_menu_path"])) {
		$discuss_menu_path = $conf["tm_discuss_menu_path"];
	}

	// remove following metatags as we create them in tm_preprocess_html
	if (current_path() == $discuss_menu_path) {
		unset($output['canonical']);
		unset($output['og:url']);
		unset($output['og:title']);
	}
}

function tm_discuss_menu() {

	$items = array();

	// configurable menu path
	global $conf;
	$discuss_menu_path = "discuss"; // default
	if (isset($conf["tm_discuss_menu_path"])) {
		$discuss_menu_path = $conf["tm_discuss_menu_path"];
	}
	$discuss_full_path = "discussions"; // default
	if (isset($conf["tm_discuss_full_path"])) {
		$discuss_full_path = $conf["tm_discuss_full_path"];
	}

	$items[$discuss_menu_path] = array(
		'title' => '',
		'page callback' => 'tm_discuss_embed_vanilla',
		'access arguments' => array('access content')
	);

	// placeholder menu item
	$items[$discuss_full_path] = array(
		'title' => '',
		'page callback' => 'tm_discussions_placeholder',
		'access arguments' => array('access content')
	);

   return $items;
}

/* 
 * Placeholder for discussions url
 */
function tm_discussions_placeholder() {
	// won't get here as this url is caught by vanilla
	return "Discussions not installed.";
}

/*
 * Embed vanilla
 */
function tm_discuss_embed_vanilla() {

	global $conf;
	$discuss_menu_path = "discuss"; // default
	if (isset($conf["tm_discuss_menu_path"])) {
		$discuss_menu_path = $conf["tm_discuss_menu_path"];
	}

	$discuss_full_path = "discussions"; // default
	if (isset($conf["tm_discuss_full_path"])) {
		$discuss_full_path = $conf["tm_discuss_full_path"];
	}

	// add trailing slash if path is /discuss
	if (request_uri() == "/" . $discuss_menu_path) {
		drupal_goto($discuss_menu_path . '/');
		return;
	}

	global $conf;
	if (isset($conf["tm_discuss_menu_hide"])) {
		if ($conf["tm_discuss_menu_hide"]) {
			// set cookie so we can show the menu item
			user_cookie_save(array('show_discuss_menu'=>'true'));
		}
	}

	global $conf;
	global $user;
	$loaded = user_load($user->uid);

	$embed_script = '<script type="text/javascript" src="/' . $discuss_full_path . '/js/embed.js"></script>';

	// hide title as it's displayed on the forum anyway
	drupal_add_css('#page-title { display: none; }', 'inline');

	$signedIn = user_is_logged_in(); //(isset($user->uid) && ($user->uid > 0)) ? true : false; 

	if (($signedIn) && (!in_array("approved user", $loaded->roles))) {

    	// show approval link
    	$who_flagged = flag_get_entity_flags("user", $loaded->uid, "approval_requested_by_user");
    	if (sizeof($who_flagged) > 0) {
      		foreach ($who_flagged as $flagger) {
        		$difference = time() - $flagger->timestamp;
      		}
      		$flagged_time = format_interval($difference, 1) . " ago";
			$approval_link = l(t('Approval requested (' . $flagged_time . ')'), 'javascript:jq_approval_already_requested();', array('fragment' => '','external'=>true));
		} 
		else {
			$approval_link = l(t('Approve my account'), 'javascript:jq_request_approval(' . $loaded->uid . ')', array('fragment' => '','external'=>true, 'attributes' => array('class' => array('approval-link'))));
		}

		// tell user they need to be approved
		drupal_set_message("Your profile needs to be approved before you can join the discussion. " . $approval_link, 'page_notice');

	} else if (!$signedIn) {
		$signup_message = "Welcome to " . $conf["tm_site_name"] . " Discuss. Want to join the discussion? ";
		if (isset($conf["tm_discuss_signup_message"])) {
			$signup_message = $conf["tm_discuss_signup_message"];
		}
		drupal_set_message($signup_message . "<a href='/user/register'>Sign up now</a> or <a href='javascript:jq_login_signup_box();'>Log In</a>.");
	} else {
		// welcome message
		//drupal_get_messages();
		//drupal_set_message("Welcome to " . $conf["tm_site_name"] . " Discuss. Have your say and share your ideas with the community."); // page_notice
	}

	drupal_set_title("Discuss");
	return $embed_script;

}

/**
 * Add html meta tags
 * Called from tm/themes/template.php
 */
function tm_discuss_preprocess_html(&$variables, $hook) {

	global $conf;
	
	// add tag
	$variables['classes_array'][] = "tm_discuss";

	// gererate canonical url
	$canonical = url('/' . $discuss_menu_path, array('absolute' => TRUE)) . "/";

	// canonical url
	$meta = array(
	  '#tag' => 'link', 
	  '#attributes' => array(
	    'rel' => 'canonical', 
	    'href' => $canonical,
	  ),
	);
	drupal_add_html_head($meta, 'canonical');

	// og:url
	$meta = array(
	  '#tag' => 'meta', 
	  '#attributes' => array(
	    'name' => 'og:url', 
	    'content' => $canonical,
	  ),
	);
	drupal_add_html_head($meta, 'og:url');

	// og:title
	if (isset($conf['tm_discuss_meta_og_title'])) {
	  $meta = array(
	    '#tag' => 'meta', 
	    '#attributes' => array(
	      'name' => 'og:title', 
	      'content' => $conf['tm_discuss_meta_og_title'],
	    ),
	  );
	  drupal_add_html_head($meta, 'og:title');
	}

	// og:image
	if (isset($conf['tm_discuss_meta_og_image'])) {
	  $meta = array(
	    '#tag' => 'meta', 
	    '#attributes' => array(
	      'name' => 'og:image', 
	      'content' => $conf['tm_discuss_meta_og_image'],
	    ),
	  );
	  drupal_add_html_head($meta, 'og:image');
	}

	// description
	if (isset($conf['tm_discuss_meta_description'])) {
	  $meta = array(
	    '#tag' => 'meta', 
	    '#attributes' => array(
	      'name' => 'description',
	      'property' => 'og:description',
	      'content' => $conf['tm_discuss_meta_description'],
	    ),
	  );
	  drupal_add_html_head($meta, 'description');
	}
}


?>