<?php

/* 

Custom module for vanilla integration
This also requires orchid module (custom)
Install vanilla to /discussions/ and use embed to host discussion on /discuss page
Install steps:

Install Vanilla
- Create /discussions folder in Drupal root
- Clone vanilla "git clone https://github.com/vanilla/vanilla discussions"
- Create mysql database for vanilla, etc.
- Download http://vanillaforums.org/addon/jsconnect-plugin
- Download http://vanillaforums.org/addon/jsconnectautosignin-plugin
- Visit /discussions in web browser and install vanilla
- Setup jsconnect plugin
- In jsconnect plugin set "This is trusted connection and can sync roles & permissions."
- In jsconnect plugin set "Make this connection your default signin method."
- Add roles for chapter leader, non-validated, moderator, approved user, administrator (to sync)
- Set embed
- $Configuration['Garden']['Profile']['ShowActivities'] = FALSE;

Drupal
- Enable drupal modules: "drush en orchid tm_discuss"
- Go to /admin/config/vanilla/orchid to configure
- Set client id, secret key from vanilla setttings
- Set Vanilla forum URL to /discussions/
- Enable avatar sync

Additional references: 
- Orchid module - https://www.drupal.org/project/orchid
- Orchid instructions - https://www.drupal.org/node/1117992

*/

function tm_discuss_menu() {

   $items = array();

   $items['discuss'] = array(
   	  'title' => '',
      'page callback' => 'tm_discuss_embed_vanilla',
      'access arguments' => array('access content')
   );

   return $items;
}

function tm_discuss_embed_vanilla() {

	// add trailing slash if path is /discuss
	if (request_uri() == "/discuss") {
		drupal_goto('discuss/');
		return;
	}

	global $conf;
	global $user;
	$loaded = user_load($user->uid);

	$embed_script = '<script type="text/javascript" src="/discussions/js/embed.js"></script>';

	// hide title as it's displayed on the forum anyway
	drupal_add_css('#page-title { display: none; }', 'inline');

	$signedIn = (isset($user->uid) && ($user->uid > 0)) ? true : false; 

	if (($signedIn) && (!in_array("approved user", $loaded->roles))) {

    	// show approval link
    	$who_flagged = flag_get_entity_flags("user", $loaded->uid, "approval_requested_by_user");
    	if (sizeof($who_flagged) > 0) {
      		foreach ($who_flagged as $flagger) {
        		$difference = time() - $flagger->timestamp;
      		}
      		$flagged_time = format_interval($difference, 1) . " ago";
			$approval_link = l(t('Approval requested (' . $flagged_time . ')'), 'javascript:jq_approval_already_requested();', array('fragment' => '','external'=>true));
		} 
		else {
			$approval_link = l(t('Approve my account'), 'javascript:jq_request_approval(' . $loaded->uid . ')', array('fragment' => '','external'=>true, 'attributes' => array('class' => array('approval-link'))));
		}

		// tell user they need to be approved
		drupal_set_message("Your profile needs to be approved before you can join the discussion. " . $approval_link, 'page_notice');

	} else if (!$signedIn) {
		drupal_set_message("Welcome to " . $conf["tm_site_name"] . " Discuss. Want to join the discussion? <a href='/user/register'>Sign up now</a> or <a href='/user/login'>Log In</a>.");
	} else {
		// welcome message
		//drupal_get_messages();
		//drupal_set_message("Welcome to " . $conf["tm_site_name"] . " Discuss. Have your say and share your ideas with the community."); // page_notice
	}

	drupal_set_title("Discuss");
	return $embed_script;

}

?>