<?php
/**
 * @file
 * Code for the tm_newsfeed feature.
 *
 * Installation:
 * To schedule notifications you must run the following command daily:
 * drush newsfeed-schedule-deliveries
 *
 * Drush tests
 * drush newsfeed-test --member-email=user@example --date-range=weekly
 * drush newsfeed-test-worker --member-email=user@example --type=weekly
 * 
 */

include "tm_newsfeed.class.inc";
include "tm_newsfeed.email.inc";
include "tm_newsfeed.builder.inc";
include "tm_newsfeed.marketplace.inc";
include "tm_newsfeed.blog.inc";
include "tm_newsfeed.discuss.inc";
include "tm_newsfeed.preview.inc";

/*
* Implements hook_menu()
*/
function tm_newsfeed_menu() {

  $items['admin/newsfeed/notification_preview'] = array(
    'title' => 'Notification Email Test',
    'page callback' => 'tm_newsfeed_admin_notification_preview',
    'page arguments' => array(2),
    'access callback' => 'tm_newsfeed_admin_notification_preview_callback',
    'type' => MENU_CALLBACK,
  );

  return $items;
}
