<?php
/**
 * @file
 * Code for the TM Status Updates feature.
 */

// tm_status_updates.module - status updates

include_once 'tm_status_updates.features.inc';
include_once 'tm_status_updates.install';
include_once 'tm_status_updates.builder.inc';
include_once 'tm_status_updates.controller.inc';
include_once 'tm_status_updates.display.inc';
include_once 'tm_status_updates.handle_update.inc';
include_once 'tm_status_updates.handle_edit.inc';
include_once 'tm_status_updates.handle_remove.inc';
include_once 'tm_status_updates.handle_moderate.inc';
include_once 'tm_status_updates.handle_preview.inc';
include_once 'tm_status_updates.handle_promote.inc';
include_once 'tm_status_updates.render.inc';
include_once 'tm_status_updates.frontpage.inc';
include_once 'tm_status_updates.post_form.inc';
include_once 'tm_status_updates.recommended.inc';
include_once 'tm_status_updates.view_count.inc';
include_once 'tm_status_updates.drush.inc';


/**
 * Implements hook_menu()
 */
function tm_status_updates_menu() {

  $items['newsfeed'] = array(
    'title' => 'News feed',
    'page callback' => 'tm_status_updates_display_newsfeed',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_display_callback',
    'type' => MENU_CALLBACK,
  );

  $items['newsfeed/global'] = array(
    'title' => 'Global news feed',
    'page callback' => 'tm_status_updates_display_global',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_display_callback',
    'type' => MENU_CALLBACK,
  );

  $items['newsfeed/tags/%'] = array(
    'title' => 'Tagged status updates',
    'page callback' => 'tm_status_updates_display_tags',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_display_callback',
    'type' => MENU_CALLBACK,
  );

  $items['newsfeed/search/%'] = array(
    'title' => 'Search status updates',
    'page callback' => 'tm_status_updates_display_search',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_display_callback',
    'type' => MENU_CALLBACK,
  );

  $items['newsfeed/near'] = array(
    'title' => 'Nearby status updates',
    'page callback' => 'tm_status_updates_display_near',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_display_callback',
    'type' => MENU_CALLBACK,
  );

  $items['newsfeed/near/%'] = array(
    'title' => 'Nearby status updates',
    'page callback' => 'tm_status_updates_display_near',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_display_callback',
    'type' => MENU_CALLBACK,
  );

  $items['newsfeed/load'] = array(
    'title' => 'Load more news feed',
    'page callback' => 'tm_status_updates_display_ajax',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_display_callback',
    'type' => MENU_CALLBACK,
  );

  $items['user/%user/status/update'] = array(
    'title' => 'Update status',
    'page callback' => 'tm_status_updates_update_status_ajax',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_update_status_check',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['user/%user/status/edit'] = array(
    'title' => 'Edit status',
    'page callback' => 'tm_status_updates_edit_status_ajax',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_edit_status_check',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['user/%user/status/edit_form'] = array(
    'title' => 'Edit form ajax',
    'page callback' => 'tm_status_updates_edit_form_ajax',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_edit_status_check',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['user/%user/status/preview_link'] = array(
    'title' => 'Preview URL',
    'page callback' => 'tm_status_updates_preview_link_ajax',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_preview_link_check',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['user/%user/status/remove'] = array(
    'title' => 'Remove status',
    'page callback' => 'tm_status_updates_remove_status_ajax',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_remove_status_check',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['user/%user/status/moderate'] = array(
    'title' => 'Moderate status',
    'page callback' => 'tm_status_updates_moderate_status_ajax',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_moderate_status_check',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['user/%user/status/promote'] = array(
    'title' => 'Promote status',
    'page callback' => 'tm_status_updates_promote_status_ajax',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_promote_status_check',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  $items['user/%user/status/unpromote'] = array(
    'title' => 'Un-promote status',
    'page callback' => 'tm_status_updates_unpromote_status_ajax',
    'page arguments' => array(1),
    'access callback' => 'tm_status_updates_promote_status_check',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Check whether the current path is on the newsfeed
 * ie: /newsfeed/global etc
 */
function tm_status_updates_check_newsfeed_path() {

  $path = current_path();

  // match /newsfeed
  if ($path == "newsfeed") {
    return true;
  }

  // match /newsfeed/global
  if (strpos($path, "newsfeed/") === 0) {
    return true;
  }
 
}

/**
 * Get the newsfeed subpath
 * ie: /newsfeed/global returns 'global'
 */
function tm_status_updates_get_newsfeed_subpath() {

  if (!tm_status_updates_check_newsfeed_path()) {
    return null;
  }

  $parts = explode("/", current_path());
  if (isset($parts[1])) {
    return $parts[1];
  }

  return null;
 
}

/**
 * Update meta tags for /newsfeed pages
 */
function tm_status_updates_metatag_metatags_view_alter(&$output, $instance) {

  // check that we are on newsfeed path
  if (!tm_status_updates_check_newsfeed_path()) {
    return;
  }

  // remove following metatags as we create them in tm_status_updates_preprocess_html
  unset($output['og:title']);
  unset($output['dcterms.title']);

}

/**
 * Add html meta tags
 * Called from tm/themes/template.php
 */
function tm_status_updates_preprocess_html(&$variables, $hook) {

  global $conf;

  // Check that we are on newsfeed page
  if (!tm_status_updates_check_newsfeed_path()) {
    return;
  }

  // add tag
  $variables['classes_array'][] = "tm_status_updates";

  // og:title
  if (isset($conf['tm_status_updates_meta_og_title'])) {

    // append subpath to title so it's unique
    $title = $conf['tm_status_updates_meta_og_title'];
    $sub_title = tm_status_updates_get_newsfeed_subpath();
    if ($sub_title != "") {
      $title .= " | " . ucfirst($sub_title);
    }

    $meta = array(
      '#tag' => 'meta', 
      '#attributes' => array(
        'property' => 'og:title', 
        'content' => $title,
      ),
    );
    drupal_add_html_head($meta, 'og:title');

    $meta = array(
      '#tag' => 'meta', 
      '#attributes' => array(
        'property' => 'dcterms.title', 
        'content' => $title,
      ),
    );
    drupal_add_html_head($meta, 'dcterms.title');
  }

  // og:image
  if (isset($conf['tm_status_updates_meta_og_image'])) {
    $meta = array(
      '#tag' => 'meta', 
      '#attributes' => array(
        'property' => 'og:image', 
        'content' => $conf['tm_status_updates_meta_og_image'],
      ),
    );
    drupal_add_html_head($meta, 'og:image');
  }

  // description
  if (isset($conf['tm_status_updates_meta_description'])) {
    $meta = array(
      '#tag' => 'meta', 
      '#attributes' => array(
        'name' => 'description',
        'property' => 'og:description',
        'content' => $conf['tm_status_updates_meta_description'],
      ),
    );
    drupal_add_html_head($meta, 'description');
  }
}

/**
 * Approval callback for viewing newsfeed
 */
function tm_status_updates_display_callback() {
  return true;
}



