<?php
/**
 * @file tm_notifications.module
 * 
 * @author Daniel Silva (daniel.silva@flipside.org)
 * 
 */

module_load_include('inc', 'tm_notifications', 'tm_notifications_TMNotification');
 
/**
 * Implements hook_menu()
 */
function tm_notifications_menu() {
  $items['admin/config/tm/tm_notifications'] = array(
    'title' => 'Notifications',
    'description' => 'Settings for Travel Massive notifications.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tm_notifications_messages_admin_form'),
    'access arguments' => array('manage tm notifications'),
    'file' => 'tm_notifications.admin.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_permission()
 */
function tm_notifications_permission() {
  return array(
    'manage tm notifications' => array(
      'title' => t('Manage notifications'),
      'description' => t('Manage travel massive notifications.'),
    ),
  );
}

/**
 * Implements hook_field_extra_fields()
 * Add a new field to the user form that contain the notifications.
 * The actual form element will be created in the form_alter hook
 */
function tm_notifications_field_extra_fields() {
  $return['user']['user']  = array(
    'form' => array(
      'tm_notifications' => array(
        'label' => t('Notifications'),
        'description' => t('User notifications settings.'),
        'weight' => 50,
      ),
    )
  );

  return $return;
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function tm_notifications_form_user_profile_form_alter(&$form, &$form_state) {
  $user = $form['#user'];
  
  // Get all the registered notifications.
  $notifications = module_invoke_all('tm_notif_info');
  
  if (!empty($notifications)) {
    
    $form['tm_notifications'] = array(
      '#type' => 'fieldset',
      '#title' => t('Notification settings'),
      '#attributes' => array(
        'class' => array('field-group-fieldset')
      ),
      '#tree' => TRUE,
    );
    
    foreach ($notifications as $name => $value) {
      $notif = new TMNotification($name);
      if ($notif->isChangeAllowed()) {
        $form['tm_notifications'][$name] = array(
          '#type' => 'checkbox',
          '#title' => $notif->getLabel($value['title']),
          '#default_value' => $notif->isEnabled($user->uid),
        );
      }
    }
    
    // Attach submit handler to save the notification state.
    $form['#submit'][] = 'tm_notifications_user_form_submit';
  }
}

/**
 * Additional submit handler for form user_profile_form.
 * Used to save the notifications.
 */
function tm_notifications_user_form_submit($form, &$form_state) {
  $user = $form['#user'];
  foreach ($form_state['values']['tm_notifications'] as $key => $value) {
    $notif = new TMNotification($key);
    $notif->setForUser($user->uid, (bool) $value);
  }
}

/**
 * Implements hook_mail()
 * Compose the email to send.
 */
function tm_notifications_mail($key, &$message, $params) {
  $notif = new TMNotification($key);
  $subject = $notif->getEmailSubject();
  $msg = $notif->getEmailMessage();
  
  if (!empty($params['tokens'])) {
    $subject = token_replace($subject, $params['tokens']);
    $msg = token_replace($msg, $params['tokens']);
  }
  
  $message['subject'] = $subject;
  $message['body'][] = $msg;
  
  // Notifications that are likely to be sent to multiple user at the
  // same time should be put in a queue and sent through cron.
  // To achieve this we mimic the behaviour of queue_mail and use
  // its functions to accomplish this.
  // Whether or not to use cron is defined by the developer in the hook.
  $notifications = module_invoke_all('tm_notif_info');
  $info = $notifications[$key];
  
  if (isset($info['use_cron']) && $info['use_cron']) {
    // Store the message for sending on cron.
    _queue_mail_get_queue()->createItem($message);
    // And prevent the message from being sent instantly.
    $message['send'] = FALSE;
  }
  
}

/**
 * Notify the user using the data set through the settings form.
 * 
 * @param TMNotification $notification
 *   Notification object to use.
 * @param StdClass $account
 *   User account. (destination)
 * @param array $tokens
 *   If the message includes tokens they need to be specified here. This uses
 *   token settings.
 * 
 * @return boolean
 *   TRUE if the notification is enabled for the user and it was scheduled.
 */
function tm_notifications_notify(TMNotification $notification, $account, $tokens = array()) {
  if ($notification->isEnabled($account->uid)) {
    drupal_mail('tm_notifications', $notification->getName(), $account->mail, user_preferred_language($account), array('tokens' => $tokens));
    return TRUE;
  }
  
  return FALSE;
}

/**
 * Removes all user related notifications from the database.
 * The settings set through the admin page will not be removed.
 * 
 * @param String $notifications_name
 */
function tm_notifications_remove($notification_name) {
  db_delete('tm_notifications')
  ->condition('bundle', $notification_name)
  ->execute();
}

/**
 * Removes all entries in the database related to the given milestone.
 * This refers to the user preferences (subscribed/unsubscribed)
 * All the admin settings are also removed.
 * 
 * NOTE: When a module implementing notifications is uninstalled this function
 * should be called.
 * 
 * @param String $notifications_name
 */
function tm_notifications_purge($notification_name) {
  tm_notifications_purge_bulk(array($notification_name));
}

/**
 * Removes all entries in the database related to the given milestones.
 * This refers to the user preferences (subscribed/unsubscribed)
 * All the admin settings are also removed.
 * 
 * NOTE: When a module implementing notifications is uninstalled this function
 * should be called.
 * 
 * @param Array $notifications_name
 */
function tm_notifications_purge_bulk($notification_names) {
  module_load_include('inc', 'tm_notifications', 'tm_notifications_TMNotification');
  foreach($notification_names as $name) {
    $notif = new TMNotification($name);
    
    tm_notifications_remove($notif->getName());
    variable_delete($notif->getVarName());
  }
}
