<?php
/**
 * @file
 * Code for the TM Notifications Approval feature.
 */

include_once 'tm_notifications_approval.features.inc';

/**
 * Implements hook_tm_notif_info()
 */
function tm_notifications_approval_tm_notif_info() {
  $notification = array();
  $notification['user_approved'] = array(
    'title' => 'Member has been approved',
    'description' => 'Send the member a notification that they have been approved.',
    'use_cron' => FALSE,
    'tokens' => array(
      // The token types that have specific context. Can be multiple token types like 'term' and/or 'user'
      'token_types' => array('user', 'current-user'),
      // A boolean TRUE or FALSE whether to include 'global' context tokens like [current-user:*] or [site:*]. Defaults to TRUE.
      'global_types' => FALSE,
      // A boolean whether to include the 'Click this token to insert in into the the focused textfield' JavaScript functionality. Defaults to TRUE.
      'click_insert' => TRUE
    )
  );
  
  return $notification;
}

// note: no hook here as we perform it inside tm_user_approve (modules/custom/tm_users/tm_users.module)
