<?php
/**
 * @file tm_twitter_signin.module
 * Implementation of login with twitter.
 * This is heavily based on the twitter_signin module (http://drupal.org/project/twitter)
 * 
 * @author Daniel da Silva (daniel.silva@flipside.org)
 */

define ('TWITTER_HOST',         'http://twitter.com');
define ('TWITTER_API',          'https://api.twitter.com');
define ('TWITTER_SEARCH',       'http://search.twitter.com');
define ('TWITTER_TINYURL',      'http://tinyurl.com');

module_load_include('lib.php', 'tm_twitter_signin', 'twitter');

/**
 * Implements hook_menu().
 */
function tm_twitter_signin_menu() {
  // Signin with twitter entry point.
  $items['tm_twitter/oauth'] = array(
    'title' => 'Twitter Redirect',
    'page callback' => 'tm_twitter_signin_oauth',
    'access callback' => TRUE,
    'file' => 'tm_twitter_signin.pages.inc',
    'type' => MENU_CALLBACK,
  );
  
  // Twitter callback after acceptance.
  $items['tm_twitter/oauth/callback'] = array(
    'title' => 'Twitter Redirect',
    'page callback' => 'tm_twitter_signin_oauth_callback',
    'access callback' => TRUE,
    'file' => 'tm_twitter_signin.pages.inc',
    'type' => MENU_CALLBACK,
  );
  
  // Register page prompting data not provided by twitter.
  $items['tm_twitter/register'] = array(
    'title' => 'Twitter Register',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tm_twitter_signin_register_form'),
    'access callback' => TRUE,
    'file' => 'tm_twitter_signin.pages.inc',
    'type' => MENU_CALLBACK,
  );
  
  // Admin pages.
  // Settings for twitter like API keys
  $items['admin/config/services/tm_twitter'] = array(
    'title' => 'Twitter',
    'description' => 'Twitter settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tm_twitter_signin_admin_form'),
    'access arguments' => array('manage tm twitter settings'),
    'file' => 'tm_twitter_signin.admin.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Implements hook_permission().
 */
function tm_twitter_signin_permission() {
  return array(
    'manage tm twitter settings' => array(
      'title' => t('Manage tm twitter settings'),
    )
  );
}

/**
 * Implements hook_user_delete()
 * Deletes twitter entries when the user is deleted.
 */
function tm_twitter_signin_user_delete($account) {
  db_delete('tm_twitter_account')->condition('uid', $account->uid)->execute();
}

/**
 * Implements hook_theme().
 */
function tm_twitter_signin_theme() {
  return array(
    'tm_twitter_link_signin' => array(
      'variables' => array('url' => NULL),
      'template' => 'tm_twitter_link_signin',
      'path' => drupal_get_path('module', 'tm_twitter_signin') . '/templates',
    )
  );
}

function tm_twitter_signin_form_user_login_alter(&$form, &$form_state) {
  $form['tm_twitter_signin'] = array(
    '#markup' => theme('tm_twitter_link_signin', array('url' => url('tm_twitter/oauth')))
  );
}

/**
 * Creates a new twitter account in the database.
 *
 * @param $account_data
 *   The account data as returned by twitter.
 * @param $auth
 *  An array with the oauth_token and oauth_token_secret.
 */
function tm_twitter_account_create($account_data, $auth) {
  $result = db_insert('tm_twitter_account')
    ->fields(array(
      'twitter_uid' => $account_data['id'],
      'screen_name' => $account_data['screen_name'],
      'oauth_token' => $auth['oauth_token'],
      'oauth_token_secret' => $auth['oauth_token_secret'],
      'name' => $account_data['name'],
      'description' => $account_data['description'],
      'uid' => $account_data['drupal_uid'],
    ))
    ->execute();
  
  return $result;
}
