<?php

// tm_widgets.module

/**
 * Implement hook_menu()
 */
function tm_widgets_menu() {

   $items = array();

   $items['widgets'] = array(
      'page callback' => 'tm_widgets_home',
      'access arguments' => array('access content')
   );

   $items['widgets/public/reach'] = array(
      'page callback' => 'tm_widgets_reach',
      'access arguments' => array('access content')
   );

   $items['widgets/public/reach-results'] = array(
      'page callback' => 'tm_widgets_reach_results',
      'access arguments' => array('access content')
   );

   return $items;
}

/**
 * Show widget home
 */
function tm_widgets_home() {

  global $conf;
  print("<p><h1>" . $conf["tm_site_name"] . " Widgets</h1>
    Welcome! Here's a list of widgets:
    <br>
    <br>widgets/public/reach - Reach
    <br>
    <br>All results as returned as HTML.
    </p>");
   drupal_exit();
}

/**
 * Show reach widget
 */
function tm_widgets_reach() {

  $template_file = drupal_get_path('module', 'tm_widgets') . '/templates/reach_widget.tpl.php';
  require_once($template_file);
  drupal_exit();

}

/**
 * Show reach results
 */
function tm_widgets_reach_results() {

  $template_file = drupal_get_path('module', 'tm_widgets') . '/templates/reach_widget_results.tpl.php';
  require_once($template_file);
  drupal_exit();

}

/**
 * Helper method
 */
function tm_widgets_pluralize_members($num) {
  if ($num == 1) {
    return "member";
  } else {
    return "members";
  }
}
