<?php

// tm_leaderboard.module

include_once 'tm_leaderboard.display.inc';
include_once 'tm_leaderboard.scores.inc';

/**
 * Implement hook_menu()
 */
function tm_leaderboard_menu() {

   $items = array();

   $items['leaderboard'] = array(
    'title' => 'Chapter Leaderboard',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tm_leaderboard_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
   );

   return $items;
}

/**
 * Show leaderboard
 */
function tm_leaderboard_form() {
  
  global $conf;
  global $user;

  // Load css
  drupal_add_css(drupal_get_path('module', 'tm_leaderboard') . '/css/tm_leaderboard.css');
 
  // Check access to all rankings
  if (isset($_GET["showall"])) {
    if (!in_array("chapter leader", $user->roles) and !in_array("moderator", $user->roles)) {
      drupal_set_message("Sorry, you don't have access to global leaderboard", "warning");
      drupal_goto("/leaderboard");
    }
  }

  // Start html
  $html = "";

  // Start article
  $html .= "<article class='trilithon node view-mode-full node-by-viewer clearfix'>";

  // Set cache key
  $cache_key = "";
  if (isset($_GET["region"])) {
    $cache_key = $_GET["region"];
  }
  if (isset($_GET["country"])) {
    $cache_key = $_GET["country"];
  }
  if (isset($_GET["showall"])) {
    $cache_key = "showall";
    drupal_set_message($conf["tm_leaderboard_chapter_leaders_tip"], "help-tip");
  }

  // Fetch leaderboard from cache if available
  $cache = cache_get('tm-leaderboard-' . $cache_key, 'cache');
  if (!empty($cache) and (!isset($_GET["nocache"]))) {
    $leaderboard_html = $cache->data;
  } else {
    $leaderboard_html = tm_leaderboard_render();
    cache_set('tm-leaderboard-' . $cache_key, $leaderboard_html, 'cache', time() + 300);
  }

  // Render leaderboard
  $html .= $leaderboard_html;

  $html .= "</article>";

  $form['html'] =  array(
    '#type' => 'markup',
    '#markup' => $html);

  return $form;

}

/**
 * Add html meta tags
 * Called from tm/themes/template.php
 */
function tm_leaderboard_preprocess_html(&$variables, $hook) {

  global $conf;

  if (current_path() != "leaderboard") {
    return;
  }
  
  // og:image
  if (isset($conf['tm_insights_og_image'])) {
    $meta = array(
      '#tag' => 'meta', 
      '#attributes' => array(
        'name' => 'og:image', 
        'content' => $conf['tm_leaderboard_og_image'],
      ),
    );
    drupal_add_html_head($meta, 'og:image');
  }

  // description
  if (isset($conf['tm_leaderboard_og_description'])) {
    $meta = array(
      '#tag' => 'meta', 
      '#attributes' => array(
        'name' => 'description',
        'property' => 'og:description',
        'content' => $conf['tm_leaderboard_og_description'],
      ),
    );
    drupal_add_html_head($meta, 'description');
  }

}
