<?php
/**
 * @file
 * Code for the TM Reports feature.
 */

include_once 'tm_reports.features.inc';

function tm_reports_menu() {

   $items = array();

   $items['chapters/%/insights'] = array(
    'title' => 'Chapter insights',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tm_reports_chapter_insights'),
    'access arguments' => array('tm invite own chapters'),
    'type' => MENU_CALLBACK,
   );

   $items['admin/global_insights'] = array(
    'title' => 'Global insights',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tm_reports_global_insights'),
    'access callback' => 'tm_reports_user_is_moderator',   
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
   );

   $items['node/%/unapproved-members'] = array(
    'title' => tm_users_get_unapproved_member_label("plural"),
    'page callback' => 'tm_reports_unapproved_members_redirect',
    'page arguments' => array(1),
    'access arguments' => array('approve users'),
    'type' => MENU_CALLBACK,
   );

   $items['node/%/chapter-insights'] = array(
    'title' => t('Chapter insights'),
    'page callback' => 'tm_reports_chapter_insights_redirect',
    'page arguments' => array(1),
    'access arguments' => array('approve users'),
    'type' => MENU_CALLBACK,
   );

   return $items;
}

/**
 * Check user is moderator
 */
function tm_reports_user_is_moderator() {
  global $user;
  return (in_array("moderator", $user->roles) or in_array("administrator", $user->roles));
}

/** 
 * Redirect from chapter reports to clean URL for unapproved members
 */
function tm_reports_unapproved_members_redirect($nid) {
  $chapter = node_load($nid);
  $redirect_url = drupal_get_path_alias("node/" . $nid) . "/unapproved-members";
  drupal_goto("/" . $redirect_url);
}

/** 
 * Redirect from chapter reports to clean URL for chapter insights
 */
function tm_reports_chapter_insights_redirect($nid) {
  $chapter = node_load($nid);
  $redirect_url = drupal_get_path_alias("node/" . $nid) . "/insights";
  drupal_goto("/" . $redirect_url);
}

/**
 * Implements hook_views_query_alter().
 */
function tm_reports_views_query_alter(&$view, &$query) {
 if ($view->current_display == 'chapters_report' || $view->current_display == 'chapters_report_export') {
  _tm_reports_views_query_alter_chapter_report($view, $query);
 }

 if ($view->current_display == 'industry_report' || $view->current_display == 'industry_report_export') {
  _tm_reports_views_query_alter_industry_report($view, $query);
 }
}

/**
* Implements hook_views_pre_render().
*/
function tm_reports_views_pre_render(&$view) {
  if ($view->current_display == 'chapters_report' || $view->current_display == 'chapters_report_export') {
    _tm_reports_views_pre_render_chapter_report($view);
  }

  if ($view->current_display == 'industry_report' || $view->current_display == 'industry_report_export') {
    _tm_reports_views_pre_render_industry_report($view);
  }
}

/* Modify chapter report view query */
function _tm_reports_views_query_alter_chapter_report(&$view, &$query) {

  // Rewrite JOIN Date of Last Event and Time Ago (field_data_field_event_date table).
  $join = new views_join;
  $join->construct('field_data_field_event_date', 'field_chapter_node', 'nid', 'entity_id', array(), 'LEFT');
  $join->extra = array(
    array(
        'field' => 'entity_type',
        'value' => 'node',
    ),
    array(
        'field' => 'deleted',
        'value' => '0',
    ),
    array(
        'field' => 'field_event_date_value',
        'operator' => '>=',
        'value' => date('Y-m-d', strtotime('-1 year')),
    ),
    array(
        'field' => 'field_event_date_value',
        'operator' => '<',
        'value' => date('Y-m-d'),
    )   
  );
  $query->add_relationship('field_chapter_node__field_data_field_event_date', $join, 'node');
  
  /* Rewrite community managers JOIN */
  $join = new views_join;
  $join->construct('field_data_field_community_managers', 'node', 'nid', 'entity_id', array(), 'LEFT');
   $join->extra = array(
    array(
        'field' => 'entity_type',
        'value' => 'node',
    ),
    array(
        'field' => 'deleted',
        'value' => '0',
    ),
    /* Add new condition */
    array(
        'field' => 'entity_id',
        'value' => 'field_chapter_node__field_data_field_event_date.entity_id',
    )
  );
  $query->add_relationship('field_data_field_community_managers', $join, 'field_data_field_community_managers');

  /* JOIN next event date */
  $join = new views_join;
  $join->construct('field_data_field_event_date', 'field_chapter_node', 'nid', 'entity_id', array(), 'LEFT');
  $join->extra = array(
    array(
        'field' => 'entity_type',
        'value' => 'node',
    ),
    array(
        'field' => 'deleted',
        'value' => '0',
    ),
    array(
        'field' => 'field_event_date_value',
        'operator' => '>',
        'value' => date('Y-m-d', strtotime('now')),
    )
  );
  $query->add_relationship('field_chapter_node__field_data_field_next_event_date', $join, 'node');
  $query->fields['field_chapter_node__field_data_field_event_date_field_event__3']['table'] = 'field_chapter_node__field_data_field_next_event_date';
  
  /* Add nid field of the next event (need in the link) */
  $query->add_field(null, 'field_chapter_node__field_data_field_next_event_date.entity_id', 'next_event_date_entity_id', array('function' => 'max')); 
}

/* Modify chapter report view pre render */
function _tm_reports_views_pre_render_chapter_report(&$view) {

  // developer: uncomment to reset flag count table
  //_tm_flags_fix_flag_counts();

  // Vars for members counts
  $table = 'flagging';
  $table_alias = 'fl';
  $real_field = 'fid';

  // Add additional columns for each row
  foreach ($view->result as $i => $result) {

    // CHAPTER ID
    $chapter_id = $view->result[$i]->nid;

    // GET INSIGHTS
    $insights = _tm_reports_get_chapter_insights($chapter_id)["data_values"];

    // Last Date format
    if (is_numeric($i) && (!empty($view->result[$i]->field_field_event_date[0]['raw']['value']))) {

      // Change Date format
      $event_date = strtotime($view->result[$i]->field_field_event_date[0]['raw']['value']);
      $formatted_date = date("Y-m-d", $event_date);
      $view->result[$i]->field_field_event_date[0]['rendered']['#markup'] = $formatted_date;
      
      // Link date to event
      $event_nid = $view->result[$i]->field_chapter_node_nid;
      $url = 'node/'.$event_nid;
      $interval = format_interval((time() - $event_date) , 1) . t(' ago');
      $event_time_ago_link = l($interval, $url);
      $view->result[$i]->field_field_event_date_1[0]['rendered']['#markup'] = "<span style='white-space: nowrap;'>" . $event_time_ago_link . "</span>";     
    }

    // Next Date format
    if (is_numeric($i) && (!empty($view->result[$i]->field_field_event_date_3[0]['raw']['value']))) {
      // Change Date format
      $event_date = strtotime($view->result[$i]->field_field_event_date_3[0]['raw']['value']);
      $interval = format_interval(($event_date - time()) , 1);
      $next_event_nid = $view->result[$i]->next_event_date_entity_id;
      $url = 'node/'.$next_event_nid;
      $next_event_link = l($interval, $url);        
      $view->result[$i]->field_field_event_date_3[0]['rendered']['#markup'] = $next_event_link;   
    }

    // NEW MEMBERS PAST 30 DAYS
    $view->field["members_30_days_total"] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, "members_30_days_total", "New Members (30 Days)");
    $view->field["members_30_days_total"]->view->result[$i]->members_30_days_total = $insights["members_30_days_total"];

    // NEW MEMBERS PAST 90 DAYS
    $view->field["members_90_days_total"] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, "members_90_days_total", "New Members (90 Days)");
    $view->field["members_90_days_total"]->view->result[$i]->members_90_days_total = $insights["members_90_days_total"];

     // MEMBERSHIP GROWTH % PAST 30 DAYS
    $view->field["members_30_days_pct"] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, "members_30_days_pct", "% Growth (30 Days)");
    $view->field["members_30_days_pct"]->view->result[$i]->members_30_days_pct = $insights["members_30_days_pct"];

    // MEMBERSHIP GROWTH % PAST 90 DAYS
    $view->field["members_90_days_pct"] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, "members_90_days_pct", "% Growth (90 Days)");
    $view->field["members_90_days_pct"]->view->result[$i]->members_90_days_pct = $insights["members_90_days_pct"];

    // TOTAL MEMBERS
    $view->field["members_total"] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, "members_total", "Total Members");
    $view->field["members_total"]->view->result[$i]->members_total = $insights["members_total"];

    // TOTAL APPROVED MEMBERS
    $view->field["members_approved_total"] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, "members_approved_total", "Total " . tm_users_get_approved_member_label("plural"));
    $view->field["members_approved_total"]->view->result[$i]->members_approved_total = $insights["members_approved_total"];

    // TOTAL UNAPPROVED MEMBERS
    $view->field["members_unapproved_total"] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, "members_unapproved_total", "Total " . tm_users_get_unapproved_member_label("plural"));
    $view->field["members_unapproved_total"]->view->result[$i]->members_unapproved_total = $insights["members_unapproved_total"];

    // % UNAPPROVED MEMBERS
    $view->field["members_unapproved_pct"] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, "members_unapproved_pct", "% " . tm_users_get_unapproved_member_label("plural"));
    $view->field["members_unapproved_pct"]->view->result[$i]->members_unapproved_pct = $insights["members_unapproved_pct"];

  }
}

/**
 * Calculate stats for chapter
 * NOTE: Cached
 */
function _tm_reports_get_chapter_insights($chapter_id) {

  // check cache
  $cache = cache_get('tm-reports-get-chapter-insights-' . $chapter_id, 'cache');
  if (!empty($cache)) {
    return $cache->data;
  }

  $insights = array();

  $flag = flag_get_flag('signup', NULL);
  $approved_role = user_role_load_by_name("approved user");
  $days_ago_30 = time() - (60 * 60 * 24 * 30); // 30 days ago
  $days_ago_90 = time() - (60 * 60 * 24 * 90); // 90 days ago

  // NEXT EVENT DATE
  // Fetch the nearest upcoming event that references a particular chapter.
  // Only returns one event, the one with the closest starting date.
  // Fetch the current and make sure it's UTC and user-defined timezone.
  $current_date = new DateTime('now', new DateTimeZone('UTC'));
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_chapter', 'target_id', $chapter_id)
    ->fieldCondition('field_event_date', 'value2', $current_date->format('Y-m-d H:i:s'), '>=')
    ->fieldOrderBy('field_event_date', 'value2', 'ASC')
    ->range(0,1);
  $result = $query->execute();

  // Initialize time_until.
  $time_until = NULL;

  $next_event_time = "No upcoming events";
  if (isset($result['node'])) {
    $next_event_array = array_keys($result['node']);
    $next_event = node_load($next_event_array[0]);
    $event_date = field_get_items('node',$next_event,'field_event_date');
    
    // Create datetime object and ensure UTC timezone, instead of user-defined timezone.
    $event_timezone = _tm_get_event_timezone($next_event);
    $event_datetime = new DateTime($event_date[0]['value'], new DateTimeZone($event_timezone));
    //$time_until = format_interval($event_datetime->format('U') - $current_date->format('U'), 2);
    $next_event_time = _tm_event_time_elapsed($event_datetime->format('U') - $current_date->format('U'));
    if ($time_until == "0 seconds") {
      $next_event_time = "Event now";
    }
  }
  $insights["next_event_time"] = $next_event_time;

  // LAST EVENT DATE
  // Fetch the nearest upcoming event that references a particular chapter.
  // Only returns one event, the one with the closest starting date.
  // Fetch the current and make sure it's UTC and user-defined timezone.
  $current_date = new DateTime('now', new DateTimeZone('UTC'));
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->propertyCondition('status', 1)
    ->fieldCondition('field_chapter', 'target_id', $chapter_id)
    ->fieldCondition('field_event_date', 'value2', $current_date->format('Y-m-d H:i:s'), '<=')
    ->fieldOrderBy('field_event_date', 'value2', 'DESC')
    ->range(0,1);
  $result = $query->execute();

  // Initialize time_until.
  $time_until = NULL;

  $last_event_time = "No past events";
  if (isset($result['node'])) {
    $next_event_array = array_keys($result['node']);
    $next_event = node_load($next_event_array[0]);
    $event_date = field_get_items('node',$next_event,'field_event_date');
    
    // Create datetime object and ensure UTC timezone, instead of user-defined timezone.
    $event_timezone = _tm_get_event_timezone($next_event);
    $event_datetime = new DateTime($event_date[0]['value'], new DateTimeZone($event_timezone));
    //$time_until = format_interval($event_datetime->format('U') - $current_date->format('U'), 2);
    $last_event_time = _tm_event_time_elapsed($current_date->format('U') - $event_datetime->format('U'));
  }
  $insights["last_event_time"] = $last_event_time . " ago";

  // NUMBER OF EVENTS PAST YEAR
  $query_sql = "SELECT COUNT(*) total FROM {field_data_field_event_date} e 
  LEFT JOIN field_data_field_chapter on field_data_field_chapter.entity_id = e.entity_id
  WHERE field_data_field_chapter.entity_type = 'node'
  AND field_data_field_chapter.field_chapter_target_id = :chapter_id
  AND e.entity_type = 'node' AND field_event_date_value >= DATE_SUB(NOW(),INTERVAL 1 YEAR);";
  $query = db_query($query_sql, array(':chapter_id' => $chapter_id))->fetch();
  $insights["num_events_past_12_months"] = $query->total;

  // NEW MEMBERS PAST 30 DAYS
  $query_sql = "SELECT COUNT(*) total FROM {flagging} f WHERE f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id AND timestamp >= :time_ago";
  $query = db_query($query_sql, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':time_ago' => $days_ago_30))->fetch();
  $insights["members_30_days_total"] = $query->total;

  // NEW MEMBERS PAST 90 DAYS
  $query_sql = "SELECT COUNT(*) total FROM {flagging} f WHERE f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id AND timestamp >= :time_ago";
  $query = db_query($query_sql, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':time_ago' => $days_ago_90))->fetch();
  $insights["members_90_days_total"] = $query->total;

   // MEMBERSHIP GROWTH % PAST 30 DAYS
  $query_sql = "SELECT COUNT(*) total FROM {flagging} f WHERE f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id AND timestamp < :time_ago";
  $query = db_query($query_sql, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':time_ago' => $days_ago_30))->fetch();
  $members_30_days_ago = $query->total;
  $members_30_days_pct = 0;
  if ($members_30_days_ago > 0) {      
    $members_30_days_pct = round((($insights["members_30_days_total"] / $members_30_days_ago) * 100), 0);
  }
  $insights["members_30_days_pct"] = $members_30_days_pct;

  // MEMBERSHIP GROWTH % PAST 90 DAYS
  $query_sql = "SELECT COUNT(*) total FROM {flagging} f WHERE f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id AND timestamp < :time_ago";
  $query = db_query($query_sql, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':time_ago' => $days_ago_90))->fetch();
  $members_90_days_ago = $query->total;
  $members_90_days_pct = 0;
  if ($members_90_days_ago > 0) {      
    $members_90_days_pct = round((($insights["members_90_days_total"] / $members_90_days_ago) * 100), 0);
  }
  $insights["members_90_days_pct"] = $members_90_days_pct;

  // TOTAL MEMBERS
  $query_sql = "SELECT COUNT(*) total FROM {flagging} f WHERE f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id";
  $query = db_query($query_sql, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id))->fetch();
  $members_total = $query->total;
  if ($members_total == 0) {
    $members_total = 1; // prevent div0
  }
  $insights["members_total"] = $members_total;

  // TOTAL APPROVED MEMBERS
  $query_sql = "SELECT COUNT(DISTINCT users_roles.uid) total FROM {flagging} f RIGHT JOIN users_roles ON users_roles.uid = f.uid WHERE users_roles.rid = :role_id AND f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id";
  $query = db_query($query_sql, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':role_id' => $approved_role->rid))->fetch();
  $members_approved_total = $query->total;
  $insights["members_approved_total"] = $members_approved_total;
  if ($members_approved_total == 0) { 
    $members_approved_total = 1; // prevent division by zero
  }

  // TOTAL UNAPPROVED MEMBERS
  $members_unapproved_total = $members_total - $members_approved_total;
  $insights["members_unapproved_total"] = $members_unapproved_total;  

  // % APPROVED MEMBERS
  $members_unapproved_pct = 0;
  if (($members_total > 0) && ($members_approved_total > 0)) {
    $members_unapproved_pct = round((($members_approved_total / $members_total) * 100), 0);
  }
  $insights["members_approved_pct"] = $members_unapproved_pct;

  // % UNAPPROVED MEMBERS
  $members_unapproved_pct = 0;
  if (($members_total > 0) && ($members_unapproved_total > 0)) {
    $members_unapproved_pct = round((($members_unapproved_total / $members_total) * 100), 0);
  }
  $insights["members_unapproved_pct"] = $members_unapproved_pct;

  // NUM MEMBERS WITH A SEGMENT
  $query_sql = "SELECT COUNT(DISTINCT users_roles.uid) total FROM {flagging} f
  LEFT JOIN users_roles ON users_roles.uid = f.uid 
  RIGHT JOIN field_data_field_segment on f.uid = field_data_field_segment.entity_id 
  WHERE field_data_field_segment.entity_id is not null
  AND users_roles.rid = :role_id
  AND f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id";
  $query = db_query($query_sql, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':role_id' => $approved_role->rid))->fetch();
  $insights["members_approved_with_segment"] = $query->total;

  // NUM MEMBERS WITHOUT A SEGMENT
  $insights["members_approved_without_segment"] = $insights["members_approved_total"] - $insights["members_approved_with_segment"];

  // % MEMBERS WITH AN INDUSTRY SEGMENT
  $members_with_segment_pct = 0;
  if (($insights["members_approved_with_segment"] > 0) && ($members_approved_total > 0)) {
    $members_with_segment_pct = round((($insights["members_approved_with_segment"] / $members_approved_total) * 100), 0);
  }
  $insights["members_with_segment_pct"] = $members_with_segment_pct;

  // NUMBER OF SIGNED IN MEMBERS TODAY (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid RIGHT JOIN {flagging} f ON f.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 1 DAY) AND f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id AND f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id";
  $signed_in_today_chapter = db_query($query, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_24_hours_chapter"] = $signed_in_today_chapter->amount;

  // NUMBER OF SIGNED IN MEMBERS 7 DAYS (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid RIGHT JOIN {flagging} f ON f.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 7 DAY) AND f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id";
  $signed_in_7_days_chapter = db_query($query, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_7_days_chapter"] = $signed_in_7_days_chapter->amount;

  // NUMBER OF SIGNED IN MEMBERS 30 DAYS (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid RIGHT JOIN {flagging} f ON f.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 30 DAY) AND f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id";
  $signed_in_30_days_chapter = db_query($query, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_30_days_chapter"] = $signed_in_30_days_chapter->amount;

  // NUMBER OF SIGNED IN MEMBERS 90 DAYS (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid RIGHT JOIN {flagging} f ON f.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 90 DAY) AND f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id";
  $signed_in_90_days_chapter = db_query($query, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_90_days_chapter"] = $signed_in_90_days_chapter->amount;

  // NUMBER OF MEMBERS WHO HAVEN'T SIGNED IN SINCE 90 DAYS (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid RIGHT JOIN {flagging} f ON f.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) < DATE_SUB(NOW(), INTERVAL 90 DAY) AND f.fid = :fid AND f.entity_type = 'node' AND f.entity_id = :chapter_id";
  $signed_in_older_than_90_days_chapter = db_query($query, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id, ':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_older_than_90_days_chapter"] = $signed_in_older_than_90_days_chapter->amount;

  // % OF SIGNED IN MEMBERS TODAY
  $insights["pct_signedin_members_24_hours_chapter"] = round(($signed_in_today_chapter->amount / $members_approved_total) * 100, 0);

  // % OF SIGNED IN MEMBERS 7 DAYS
  $insights["pct_signedin_members_7_days_chapter"] = round(($signed_in_7_days_chapter->amount / $members_approved_total) * 100, 0);

  // % OF SIGNED IN MEMBERS 30 DAYS
  $insights["pct_signedin_members_30_days_chapter"] = round(($signed_in_30_days_chapter->amount / $members_approved_total) * 100, 0);

  // % OF SIGNED IN MEMBERS 90 DAYS
  $insights["pct_signedin_members_90_days_chapter"] = round(($signed_in_90_days_chapter->amount / $members_approved_total) * 100, 0);

  // % OF MEMBERS WHO HAVEN'T SIGNED IN SINCE 90 DAYS
  $insights["pct_signedin_members_older_than_90_days_chapter"] = (100 - round(($signed_in_90_days_chapter->amount / $members_approved_total) * 100, 0));

  // NUMBER OF MEMBERS WITH HOME CHAPTER
  $query = "SELECT COUNT(*) AS amount FROM flagging f RIGHT JOIN field_data_field_home_chapter hc ON hc.entity_id = f.uid WHERE f.fid = :fid AND f.entity_id = :chapter_id AND hc.field_home_chapter_target_id = :chapter_id";
  $num_members_with_home_chapter = db_query($query, array(':fid' => $flag->fid, ':chapter_id' => $chapter_id))->fetch();
  $insights["num_members_with_home_chapter"] = $num_members_with_home_chapter->amount;
  $insights["pct_members_with_home_chapter"] = round(($insights["num_members_with_home_chapter"] / $members_total) * 100, 0);
  $insights["num_members_without_home_chapter"] = $members_total - $num_members_with_home_chapter->amount;
  $insights["pct_members_without_home_chapter"] = round(($insights["num_members_without_home_chapter"] / $members_total) * 100, 0);

  // NUMBER OF TOTAL EVENT REGISTRATIONS
  $flag_event_register = flag_get_flag('event_register', NULL);
  $query = "SELECT COUNT(uid) AS amount FROM flagging WHERE entity_id IN (SELECT entity_id AS nid FROM field_data_field_chapter WHERE bundle = 'event' AND field_chapter_target_id = :chapter_id) AND fid = :fid";
  $num_event_registrations = db_query($query, array(':fid' => $flag_event_register->fid, ':chapter_id' => $chapter_id))->fetch();
  $insights["num_event_registrations"] = $num_event_registrations->amount;

  // NUMBER OF TOTAL EVENT WAITLISTS
  $flag_event_waitlist = flag_get_flag('event_waitlist', NULL);
  $query = "SELECT COUNT(uid) AS amount FROM flagging WHERE entity_id IN (SELECT entity_id AS nid FROM field_data_field_chapter WHERE bundle = 'event' AND field_chapter_target_id = :chapter_id) AND fid = :fid";
  $num_event_waitlists = db_query($query, array(':fid' => $flag_event_waitlist->fid, ':chapter_id' => $chapter_id))->fetch();
  $insights["num_event_waitlists"] = $num_event_waitlists->amount;

  // NUMBER OF TOTAL EVENT PAYMENTS
  $flag_event_paid = flag_get_flag('event_paid', NULL);
  $query = "SELECT COUNT(uid) AS amount FROM flagging WHERE entity_id IN (SELECT entity_id AS nid FROM field_data_field_chapter WHERE bundle = 'event' AND field_chapter_target_id = :chapter_id) AND fid = :fid";
  $num_event_payments = db_query($query, array(':fid' => $flag_event_paid->fid, ':chapter_id' => $chapter_id))->fetch();
  if ($num_event_payments->amount > 0) {
    $insights["num_event_payments"] = $num_event_payments->amount;
  }

  // NUMBER OF UNIQUE EVENT REGISTRATIONS
  $query = "SELECT COUNT(DISTINCT(uid)) AS amount FROM flagging WHERE entity_id IN (SELECT entity_id AS nid FROM field_data_field_chapter WHERE bundle = 'event' AND field_chapter_target_id = :chapter_id) AND fid = :fid";
  $num_unique_chapter_event_registrations = db_query($query, array(':fid' => $flag_event_register->fid, ':chapter_id' => $chapter_id))->fetch();
  $insights["num_unique_chapter_event_registrations"] = $num_unique_chapter_event_registrations->amount;
  $insights["pct_unique_chapter_event_registrations"] = round(($insights["num_unique_chapter_event_registrations"] / $members_approved_total) * 100, 0);

  // FREQUENCY OF EVENTS
  $flag = flag_get_flag('event_register', NULL);
  $query_sql = "SELECT AVG(amount) AS total FROM (SELECT uid, COUNT(uid) AS amount FROM flagging f WHERE entity_id IN (SELECT entity_id AS nid FROM field_data_field_chapter WHERE bundle = 'event' AND field_chapter_target_id = :chapter_id) AND f.fid = :fid GROUP BY uid) AS t2";
  $query = db_query($query_sql, array("chapter_id" => $chapter_id, ":fid" => $flag->fid))->fetch();
  $avg_event_registeration_frequency = round($query->total, 1);
  $insights['avg_event_registeration_frequency'] = $avg_event_registeration_frequency;

  // RETURN DATA
  $data_labels = tm_reports_get_insights_labels();
  $results = ["data_values" => $insights, "data_labels" => $data_labels];
  cache_set('tm-reports-get-chapter-insights-' . $chapter_id, $results, 'cache', time() + 900); // 15 mins
  return $results;
}

/**
 * Calculate global stats
 * NOTE: Cached
 */
function _tm_reports_get_global_insights() {

  // check cache
  $cache = cache_get('tm-reports-get-global-insights', 'cache');
  if (!empty($cache)) {
    return $cache->data;
  }

  $insights = array();

  $approved_role = user_role_load_by_name("approved user");
  $days_ago_30 = time() - (60 * 60 * 24 * 30); // 30 days ago
  $days_ago_90 = time() - (60 * 60 * 24 * 90); // 90 days ago
  
  // NUMBER OF FUTURE EVENTS
  $query_sql = "SELECT COUNT(*) total FROM {field_data_field_event_date} e 
  WHERE e.entity_type = 'node' AND field_event_date_value >= NOW();";
  $query = db_query($query_sql)->fetch();
  $insights["num_events_upcoming"] = $query->total;

  // NUMBER OF EVENTS PAST MONTH
  $query_sql = "SELECT COUNT(*) total FROM {field_data_field_event_date} e 
  LEFT JOIN field_revision_field_is_partner_event p on e.entity_id = p.entity_id
  WHERE p.entity_type = 'node' AND field_is_partner_event_value = 0
  AND e.entity_type = 'node' AND field_event_date_value >= DATE_SUB(NOW(),INTERVAL 30 DAY);";
  $query = db_query($query_sql)->fetch();
  $insights["num_events_past_30_days"] = $query->total;

  // NUMBER OF EVENTS PAST YEAR
  $query_sql = "SELECT COUNT(*) total FROM {field_data_field_event_date} e 
  LEFT JOIN field_revision_field_is_partner_event p on e.entity_id = p.entity_id
  WHERE p.entity_type = 'node' AND field_is_partner_event_value = 0
  AND e.entity_type = 'node' AND field_event_date_value >= DATE_SUB(NOW(),INTERVAL 1 YEAR);";
  $query = db_query($query_sql)->fetch();
  $insights["num_events_past_12_months"] = $query->total;

  // NUMBER OF PARTNER EVENTS PAST MONTH
  $query_sql = "SELECT COUNT(*) total FROM {field_data_field_event_date} e 
  LEFT JOIN field_revision_field_is_partner_event p on e.entity_id = p.entity_id
  WHERE p.entity_type = 'node' AND field_is_partner_event_value = 1
  AND e.entity_type = 'node' AND field_event_date_value >= DATE_SUB(NOW(),INTERVAL 30 DAY);";
  $query = db_query($query_sql)->fetch();
  $insights["num_partner_events_past_30_days"] = $query->total;

  // NUMBER OF PARTNER EVENTS PAST YEAR
  $query_sql = "SELECT COUNT(*) total FROM {field_data_field_event_date} e 
  LEFT JOIN field_revision_field_is_partner_event p on e.entity_id = p.entity_id
  WHERE p.entity_type = 'node' AND field_is_partner_event_value = 1
  AND e.entity_type = 'node' AND field_event_date_value >= DATE_SUB(NOW(),INTERVAL 1 YEAR);";
  $query = db_query($query_sql)->fetch();
  $insights["num_partner_events_past_12_months"] = $query->total;

  // ALL NEW MEMBERS PAST 30 DAYS
  $query_sql = "SELECT COUNT(*) total FROM {users} u WHERE created >= :time_ago";
  $query = db_query($query_sql, array(':time_ago' => $days_ago_30))->fetch();
  $members_30_days_total = $query->total;
  $insights["members_30_days_total"] = $members_30_days_total;

  // ALL NEW MEMBERS PAST 90 DAYS
  $query_sql = "SELECT COUNT(*) total FROM {users} u WHERE created >= :time_ago";
  $query = db_query($query_sql, array(':time_ago' => $days_ago_90))->fetch();
  $members_90_days_total = $query->total;
  $insights["members_90_days_total"] = $members_90_days_total;

  // ALL MEMBERSHIP GROWTH % PAST 30 DAYS
  $query_sql = "SELECT COUNT(*) total FROM {users} u WHERE created < :time_ago";
  $query = db_query($query_sql, array(':time_ago' => $days_ago_30))->fetch();
  $members_30_days_ago = $query->total;
  $members_30_days_pct = 0;
  if ($members_30_days_ago > 0) {      
    $members_30_days_pct = round((($members_30_days_total / $members_30_days_ago) * 100), 0);
  }
  $insights["members_30_days_pct"] = $members_30_days_pct;

  // ALL MEMBERSHIP GROWTH % PAST 90 DAYS
  $query_sql = "SELECT COUNT(*) total FROM {users} u WHERE created < :time_ago";
  $query = db_query($query_sql, array(':time_ago' => $days_ago_90))->fetch();
  $members_90_days_ago = $query->total;
  $members_90_days_pct = 0;
  if ($members_90_days_ago > 0) {      
    $members_90_days_pct = round((($members_90_days_total / $members_90_days_ago) * 100), 0);
  }
  $insights["members_90_days_pct"] = $members_90_days_pct;
  
  // ALL MEMBERS
  $query_sql = "SELECT COUNT(*) total FROM {users} u";
  $query = db_query($query_sql)->fetch();
  $members_total = $query->total;
  $insights["members_total"] = $members_total;

  // ALL APPROVED MEMBERS
  $query_sql = "SELECT COUNT(DISTINCT u.uid) total FROM {users} u RIGHT JOIN users_roles ON users_roles.uid = u.uid WHERE users_roles.rid = :role_id";
  $query = db_query($query_sql, array(':role_id' => $approved_role->rid))->fetch();
  $members_approved_total = $query->total;
  $insights["members_approved_total"] = $members_approved_total;

  // TOTAL UNAPPROVED MEMBERS
  $members_unapproved_total = $members_total - $members_approved_total;
  $insights["members_unapproved_total"] = $members_unapproved_total;

  // % UNAPPROVED MEMBERS
  $members_unapproved_pct = round((($members_unapproved_total / $members_total) * 100), 0);
  $insights["members_unapproved_pct"] = $members_unapproved_pct;

  // NUM MEMBERS WITH A SEGMENT
  $query_sql = "SELECT COUNT(DISTINCT users.uid) total FROM users
  LEFT JOIN users_roles ON users_roles.uid = users.uid 
  RIGHT JOIN field_data_field_segment on users.uid = field_data_field_segment.entity_id 
  WHERE field_data_field_segment.entity_id is not null
  AND users_roles.rid = :role_id";
  $query = db_query($query_sql, array(':role_id' => $approved_role->rid))->fetch();
  $insights["members_approved_with_segment"] = $query->total;

  // NUM MEMBERS WITHOUT A SEGMENT
  $insights["members_approved_without_segment"] = $insights["members_approved_total"] - $insights["members_approved_with_segment"];

  // % MEMBERS WITH AN INDUSTRY SEGMENT
  $members_with_segment_pct = 0;
  if (($insights["members_approved_with_segment"] > 0) && ($members_approved_total > 0)) {
    $members_with_segment_pct = round((($insights["members_approved_with_segment"] / $members_approved_total) * 100), 0);
  }
  $insights["members_with_segment_pct"] = $members_with_segment_pct;

  // NUM CHAPTERS
  $query = "SELECT COUNT(*) amount FROM {node} n ".
              "WHERE n.type = :type";
  $num_chapters = db_query($query, array(':type' => "chapter"))->fetch();
  $insights["num_chapters"] = $num_chapters->amount;

  // NUMBER OF ORGANIZATIONS
  $query = "SELECT COUNT(*) amount FROM {node} n ".
              "WHERE n.type = :type";
  $num_organizations = db_query($query, array(':type' => "organization"))->fetch();
  $insights["num_organizations"] = $num_organizations->amount;

  // NUMBER OF EVENTS
  $query = "SELECT COUNT(*) amount FROM {node} n ".
              "WHERE n.type = :type";
  $num_events = db_query($query, array(':type' => "event"))->fetch();
  $insights["num_events"] = $num_events->amount;
 
  // NUMBER OF CHAPTER COUNTRIES
  $result = db_query("SELECT DISTINCT iso2, name from {field_data_field_country} f LEFT JOIN {countries_country} c ON f.field_country_iso2 = c.iso2 WHERE f.bundle = 'chapter' AND c.iso2 IS NOT NULL ORDER BY name ASC");
  $chapter_countries = $result->fetchAllKeyed();
  $num_chapter_countries = (sizeof($chapter_countries));
  $insights["num_chapter_countries"] = $num_chapter_countries;

  // NUMBER OF MEMBER COUNTRIES
  $result = db_query("SELECT DISTINCT field_user_country_iso2 from {field_data_field_user_country} ORDER BY field_user_country_iso2 ASC");
  $member_countries = $result->fetchAll();
  $num_member_countries = (sizeof($member_countries));
  $insights["num_member_countries"] = $num_member_countries;

  // NUMBER OF FOLLOWS
  $flag = flag_get_flag('follow_members', NULL);
  $query = "SELECT COUNT(*) amount FROM {flagging} f WHERE f.fid = :fid";
  $num_member_followers = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_member_followers"] = $num_member_followers->amount;

  // NUMBER OF COMPANY FOLLOWS
  $flag = flag_get_flag('follow_organizations', NULL);
  $query = "SELECT COUNT(*) amount FROM {flagging} f WHERE f.fid = :fid";
  $num_organization_followers = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_organization_followers"] = $num_organization_followers->amount;

  // NUMBER OF CONNECTIONS (member + organization follows)
  $insights["num_connections"] = $insights["num_member_followers"] + $insights["num_organization_followers"];

  // NUMBER OF MUTUAL FOLLOWS
  $flag = flag_get_flag('follow_members', NULL);
  $query = "select count(distinct flagging.uid, f2.uid) as amount from flagging inner join flagging as f2 on flagging.uid = f2.entity_id where flagging.fid = :fid and f2.fid = :fid order by flagging.uid";
  $num_mutual_followers = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_mutual_follows"] = $num_mutual_followers->amount;

  // NUMBER OF EVENT REGISTRATIONS
  $flag = flag_get_flag('event_register', NULL);
  $query = "SELECT COUNT(*) amount FROM {flagging} f WHERE f.fid = :fid";
  $num_registrations = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_event_registrations"] = $num_registrations->amount;

  // NUMBER OF WAITLISTS
  $flag = flag_get_flag('event_waitlist', NULL);
  $query = "SELECT COUNT(*) amount FROM {flagging} f WHERE f.fid = :fid";
  $num_waitlists = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_event_waitlists"] = $num_waitlists->amount;

   // NUMBER OF EVENT PAYMENTS
  $flag = flag_get_flag('event_paid', NULL);
  $query = "SELECT COUNT(*) amount FROM {flagging} f WHERE f.fid = :fid";
  $num_registrations = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_event_payments"] = $num_registrations->amount;

  // NUMBER OF UNIQUE EVENT REGISTRATIONS
  $flag = flag_get_flag('event_register', NULL);
  $query = "SELECT COUNT(DISTINCT uid) amount FROM {flagging} f WHERE f.fid = :fid";
  $num_registrations = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_unique_event_registrations"] = $num_registrations->amount;
  $insights["pct_unique_event_registrations"] = round(($insights["num_unique_event_registrations"] / $members_approved_total) * 100, 0);

  // FREQUENCY OF EVENTS
  $flag = flag_get_flag('event_register', NULL);
  $query_sql = "SELECT AVG(amount) as total FROM (SELECT uid, COUNT(uid) AS amount FROM flagging f WHERE f.fid = :fid GROUP BY uid) as t2";
  $query = db_query($query_sql, array(":fid" => $flag->fid))->fetch();
  $avg_event_registeration_frequency = round($query->total, 2);
  $insights['avg_event_registeration_frequency'] = $avg_event_registeration_frequency;

  // NUMBER OF UNIQUE WAITLISTS
  $flag = flag_get_flag('event_waitlist', NULL);
  $query = "SELECT COUNT(DISTINCT uid) amount FROM {flagging} f WHERE f.fid = :fid";
  $num_waitlists = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_unique_event_waitlists"] = $num_waitlists->amount;

   // NUMBER OF UNIQUE EVENT PAYMENTS
  $flag = flag_get_flag('event_paid', NULL);
  $query = "SELECT COUNT(DISTINCT uid) amount FROM {flagging} f WHERE f.fid = :fid";
  $num_registrations = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_unique_event_payments"] = $num_registrations->amount;

  // NUMBER OF PEOPLE WHO HAVE SENT MESSAGES
  $flag = flag_get_flag('message_sent', NULL);
  $query = "SELECT COUNT(DISTINCT uid) amount FROM {flagging} f WHERE f.fid = :fid";
  $num_waitlists = db_query($query, array(':fid' => $flag->fid))->fetch();
  $insights["num_members_sent_messages"] = $num_waitlists->amount;

  // TOTAL NUMBER OF STATUS UPDATES
  $query = "SELECT COUNT(id) amount FROM {tm_newsfeed_status_updates} WHERE is_removed = 0";
  $num_updates = db_query($query)->fetch();
  $insights["num_total_status_updates"] = $num_updates->amount;

  // TOTAL NUMBER OF PROMOTED UPDATES
  $query = "SELECT COUNT(id) amount FROM {tm_newsfeed_status_updates} WHERE is_promoted = 1 AND is_removed = 0";
  $num_promoted = db_query($query)->fetch();
  $insights["num_promoted_status_updates"] = $num_promoted->amount;

  // TOTAL NUMBER OF MODERATED UPDATES
  $query = "SELECT COUNT(id) amount FROM {tm_newsfeed_status_updates} WHERE moderator_hide = 1";
  $num_moderated = db_query($query)->fetch();
  $insights["num_moderated_status_updates"] = $num_moderated->amount;

  // TOTAL NUMBER OF LINKS SHARED
  $query = "SELECT COUNT(id) amount FROM {tm_newsfeed_status_updates} WHERE is_removed = 0 AND preview_link_id IS NOT NULL";
  $num_links = db_query($query)->fetch();
  $insights["num_total_status_links"] = $num_links->amount;

  // TOTAL NUMBER OF PREVIEW LINKS CREATED
  $query = "SELECT COUNT(id) amount FROM {tm_newsfeed_preview_links}";
  $preview_links_created = db_query($query)->fetch();
  $insights["num_total_preview_links_created"] = $preview_links_created->amount;

  // TOTAL NUMBER OF UPDATE VIEWS DAILY
  $query = "SELECT SUM(view_count) amount FROM {tm_newsfeed_view_count_daily}";
  $view_count_daily = db_query($query)->fetch();
  $insights["num_total_status_views_daily"] = $view_count_daily->amount;

  // TOTAL NUMBER OF STATUS UPDATE VIEWS
  $query = "SELECT SUM(total_view_count) amount FROM {tm_newsfeed_view_count_total}";
  $view_count = db_query($query)->fetch();
  $insights["num_total_status_views_all_time"] = $view_count->amount + $view_count_daily->amount;

  // NUMBER OF SIGNED IN MEMBERS TODAY (ALL)
  $query = "SELECT COUNT(DISTINCT uid) amount FROM users WHERE FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 1 DAY)";
  $signed_in_today = db_query($query)->fetch();
  $insights["num_signedin_members_24_hours"] = $signed_in_today->amount;

  // NUMBER OF SIGNED IN MEMBERS 7 DAYS (ALL)
  $query = "SELECT COUNT(DISTINCT uid) amount FROM users WHERE FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 7 DAY)";
  $signed_in_7_days = db_query($query)->fetch();
  $insights["num_signedin_members_7_days"] = $signed_in_7_days->amount;

  // NUMBER OF SIGNED IN MEMBERS 30 DAYS (ALL)
  $query = "SELECT COUNT(DISTINCT uid) amount FROM users WHERE FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 30 DAY)";
  $signed_in_30_days = db_query($query)->fetch();
  $insights["num_signedin_members_30_days"] = $signed_in_30_days->amount;

  // NUMBER OF SIGNED IN MEMBERS 90 DAYS (ALL)
  $query = "SELECT COUNT(DISTINCT uid) amount FROM users WHERE FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 90 DAY)";
  $signed_in_90_days = db_query($query)->fetch();
  $insights["num_signedin_members_90_days"] = $signed_in_90_days->amount;

  // NUMBER OF MEMBERS WHO HAVEN'T SIGNED IN SINCE 90 DAYS (ALL)
  $query = "SELECT COUNT(DISTINCT uid) amount FROM users WHERE FROM_UNIXTIME(access) < DATE_SUB(NOW(), INTERVAL 90 DAY)";
  $signed_in_older_than_90_days = db_query($query)->fetch();
  $insights["num_signedin_members_older_than_90_days"] = $signed_in_older_than_90_days->amount;

  // NUMBER OF SIGNED IN MEMBERS TODAY (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 1 DAY)";
  $signed_in_today_approved = db_query($query, array(':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_24_hours_approved"] = $signed_in_today_approved->amount;

  // NUMBER OF SIGNED IN MEMBERS 7 DAYS (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 7 DAY)";
  $signed_in_7_days_approved = db_query($query, array(':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_7_days_approved"] = $signed_in_7_days_approved->amount;

  // NUMBER OF SIGNED IN MEMBERS 30 DAYS (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 30 DAY)";
  $signed_in_30_days_approved = db_query($query, array(':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_30_days_approved"] = $signed_in_30_days_approved->amount;

  // NUMBER OF SIGNED IN MEMBERS 90 DAYS (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) > DATE_SUB(NOW(), INTERVAL 90 DAY)";
  $signed_in_90_days_approved = db_query($query, array(':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_90_days_approved"] = $signed_in_90_days_approved->amount;

  // NUMBER OF MEMBERS WHO HAVEN'T SIGNED IN SINCE 90 DAYS (APPROVED)
  $query = "SELECT COUNT(DISTINCT users.uid) amount FROM users RIGHT JOIN users_roles ON users_roles.uid = users.uid WHERE users_roles.rid = :role_id AND FROM_UNIXTIME(access) < DATE_SUB(NOW(), INTERVAL 90 DAY)";
  $signed_in_older_than_90_days_approved = db_query($query, array(':role_id' => $approved_role->rid))->fetch();
  $insights["num_signedin_members_older_than_90_days_approved"] = $signed_in_older_than_90_days_approved->amount;

  // % OF SIGNED IN MEMBERS TODAY
  $insights["pct_signedin_members_24_hours"] = round(($signed_in_today->amount / $members_total) * 100, 0) . " / " . round(($signed_in_today_approved->amount / $members_approved_total) * 100, 0);

  // % OF SIGNED IN MEMBERS 7 DAYS
  $insights["pct_signedin_members_7_days"] = round(($signed_in_7_days->amount / $members_total) * 100, 0) . " / " . round(($signed_in_7_days_approved->amount / $members_approved_total) * 100, 0);

  // % OF SIGNED IN MEMBERS 30 DAYS
  $insights["pct_signedin_members_30_days"] = round(($signed_in_30_days->amount / $members_total) * 100, 0) . " / " . round(($signed_in_30_days_approved->amount / $members_approved_total) * 100, 0);

  // % OF SIGNED IN MEMBERS 90 DAYS
  $insights["pct_signedin_members_90_days"] = round(($signed_in_90_days->amount / $members_total) * 100, 0) . " / " . round(($signed_in_90_days_approved->amount / $members_approved_total) * 100, 0);

  // % OF MEMBERS WHO HAVEN'T SIGNED IN SINCE 90 DAYS
  $insights["pct_signedin_members_older_than_90_days"] = (100 - round(($signed_in_90_days->amount / $members_total) * 100, 0)) . " / " . (100 - round(($signed_in_90_days_approved->amount / $members_approved_total) * 100, 0));

  // TOTAL FACEBOOK SIGNUPS
  $query_sql = "SELECT COUNT(*) total FROM field_data_field_facebook_signin_link";
  $query = db_query($query_sql)->fetch();
  $num_logins_facebook = $query->total;
  $insights['num_logins_facebook'] = $num_logins_facebook;

  // TOTAL TWITTER SIGNUPS
  $query_sql = "SELECT COUNT(*) total FROM tm_twitter_account";
  $query = db_query($query_sql)->fetch();
  $num_logins_twitter = $query->total;
  $insights['num_logins_twitter'] = $num_logins_twitter;

  // RETURN DATA
  $data_labels = tm_reports_get_insights_labels();
  $results = ["data_values" => $insights, "data_labels" => $data_labels];
  cache_set('tm-reports-get-global-insights', $results, 'cache', time() + 900); // 15 mins
  return $results;
}

/**
 * Data labels for insights table
 */
function tm_reports_get_insights_labels() {

  global $conf;

  $segment_label = "Industry Segment";
  if (isset($conf["tm_segment_label"])) {
    $segment_label = $conf["tm_segment_label"];
  }

  // DATA LABELS
  $data_labels = ["last_event_time" => "Last Event",
  "next_event_time" => "Next Event",
  "num_events_upcoming" => "Future Events",
  "num_events_past_30_days" => "Events in past 30 days",
  "num_events_past_12_months" => "Events in past 12 Months",
  "num_partner_events_past_30_days" => "Partner Events in past 30 days",
  "num_partner_events_past_12_months" => "Partner Events in past 12 Months",
  "members_30_days_total" => "New Members (30 days)",
  "members_90_days_total" => "New Members (90 days)",
  "members_30_days_pct" => "% Growth (30 days)",
  "members_90_days_pct" => "% Growth (90 days)",
  "members_total" => "Total Members",
  "members_approved_total"  => "Total " . tm_users_get_approved_member_label("plural"),
  "members_unapproved_total" => "Total " . tm_users_get_unapproved_member_label("plural"),
  "members_approved_pct" => "% " . tm_users_get_approved_member_label("plural"),
  "members_unapproved_pct" => "% " . tm_users_get_unapproved_member_label("plural"),
  "members_approved_with_segment" => tm_users_get_approved_member_label("plural") . " with " . $segment_label,
  "members_approved_without_segment" => tm_users_get_approved_member_label("plural") . " without " . $segment_label,
  "members_with_segment_pct" => "% " . tm_users_get_approved_member_label("plural") . " with " . $segment_label,
  "num_event_waitlists" => "Total Event Waitlists",
  "num_event_registrations" => "Total Event Registrations",
  "num_event_payments" => "Total Event Payments",
  "num_unique_event_waitlists" => "Total Unique Event Waitlists",
  "num_unique_event_registrations" => "Total Unique Event Registrations",
  "pct_unique_event_registrations" => "% " . tm_users_get_approved_member_label("plural") . " who have registered for events",
  "num_unique_event_payments" => "Total Unique Event Payments",
  "num_mutual_follows" => "Total Mutual Connections",
  "num_connections" => "Total Connections (All Followers)",
  "num_organization_followers" => "Total Organization Followers",
  "num_member_followers" => "Total Member Followers",
  "num_chapter_countries" => "Chapter Countries",
  "num_member_countries" => "Member Countries",
  "num_events" => "Total Number Events",
  "num_organizations" => "Number of Organizations",
  "num_members_sent_messages" => "Members who have sent Messages",
  "num_total_status_updates" => "Total Status Updates",
  "num_promoted_status_updates" => "Promoted Status Updates",
  "num_moderated_status_updates" => "Moderated Status Updates",
  "num_total_status_links" => "Total Links Shared",
  "num_total_preview_links_created" => "Total Links Previewed",
  "num_total_status_views_daily" => "Status Views (24 Hours)",
  "num_total_status_views_all_time" => "Total Status Views",
  "num_signedin_members_24_hours" => "All Active Members (24 Hours)",
  "num_signedin_members_7_days" => "All Active Members (7 Days)",
  "num_signedin_members_30_days" => "All Active Members (30 Days)",
  "num_signedin_members_90_days" => "All Active Members (90 Days)",
  "num_signedin_members_older_than_90_days" => "All Inactive Members (> 90 Days)",
  "num_signedin_members_24_hours_approved" => "Active " . tm_users_get_approved_member_label("plural") . " (24 Hours)",
  "num_signedin_members_7_days_approved" => "Active " . tm_users_get_approved_member_label("plural") . " (7 Days)",
  "num_signedin_members_30_days_approved" => "Active " . tm_users_get_approved_member_label("plural") . " (30 Days)",
  "num_signedin_members_90_days_approved" => "Active " . tm_users_get_approved_member_label("plural") . " (90 Days)",
  "num_signedin_members_older_than_90_days_approved" => "Inactive " . tm_users_get_approved_member_label("plural") . " (> 90 Days)",
  "pct_signedin_members_24_hours" => "% Active Members (24 Hours) (All/" . tm_users_get_approved_member_label("plural") . ")",
  "pct_signedin_members_7_days" => "% Active Members (7 Days) (All/" . tm_users_get_approved_member_label("plural") . ")",
  "pct_signedin_members_30_days" => "% Active Members (30 Days) (All/" . tm_users_get_approved_member_label("plural") . ")",
  "pct_signedin_members_90_days" => "% Active Members (90 Days) (All/" . tm_users_get_approved_member_label("plural") . ")",
  "pct_signedin_members_older_than_90_days" => "% Inactive Members (> 90 Days) (All/" . tm_users_get_approved_member_label("plural") . ")",
  "num_signedin_members_24_hours_chapter" => "Chapter Active Members (24 Hours)",
  "num_signedin_members_7_days_chapter" => "Chapter Active Members (7 Days)",
  "num_signedin_members_30_days_chapter" => "Chapter Active Members (30 Days)",
  "num_signedin_members_90_days_chapter" => "Chapter Active Members (90 Days)",
  "num_signedin_members_older_than_90_days_chapter" => "Chapter Inactive Members (> 90 Days)",
  "pct_signedin_members_24_hours_chapter" => "% Active Members (24 Hours)",
  "pct_signedin_members_7_days_chapter" => "% Active Members (7 Days)",
  "pct_signedin_members_30_days_chapter" => "% Active Members (30 Days)",
  "pct_signedin_members_90_days_chapter" => "% Active Members (90 Days)",
  "pct_signedin_members_older_than_90_days_chapter" => "% Inactive Members (> 90 Days)",
  "num_logins_facebook" => "Total Users Logged in with Facebook",
  "num_logins_twitter" => "Total Users Logged in with Twitter",
  "num_chapters" => "Number of Chapters",
  "num_members_with_home_chapter" => "Members from this Chapter (Home Chapter)",
  "pct_members_with_home_chapter" => "% Members from this Chapter (Home Chapter)",
  "num_members_without_home_chapter" => "Members from other Chapters",
  "pct_members_without_home_chapter" => "% Members from other Chapters",
  "num_unique_chapter_event_registrations" => "Members who have registered for events",
  "pct_unique_chapter_event_registrations" => "% " . tm_users_get_approved_member_label("plural") . " who have registered for events",
  "avg_event_registeration_frequency" => "Average Number Of Events Attended (of those who registered)"];
  return $data_labels;
}

/* Modify industry report view query */
function _tm_reports_views_query_alter_industry_report(&$view, &$query) {

  $industry_field = array();
  $v = taxonomy_vocabulary_machine_name_load("tm_segments");
  $terms = taxonomy_get_tree($v->vid, 0, 1); // get top level taxonomy
  foreach ($terms as $term) {
    // ie: $industry_field['846'] = 'tid_846';
    $industry_field[$term->tid] = 'tid_' . $term->tid;
  }
  
  foreach ($industry_field as $tid => $field_alias) {
    $join = _tm_reports_add_join_industry($field_alias, $tid);
    $query->add_relationship('th_'.$field_alias, $join, 'field_data_field_segment');
    $query->add_field('th_'.$field_alias, 'tid', $field_alias, array('function' => 'count'));
  }

  /* Add field_count for fix industry count in hook_views_pre_render */
  $query->add_field(null, 'DISTINCT(field_chapter_node.nid)', 'field_count', array('function' => 'count'));
}

/* Modify industry report view pre render */
function _tm_reports_views_pre_render_industry_report(&$view) {

  $segment_label = "Industry Segment";
  if (isset($conf["tm_segment_label"])) {
    $segment_label = $conf["tm_segment_label"];
  }

  /* Create custom column for the Industry Segment */
  $table = 'taxonomy_term_hierarchy';
  $table_alias = 'th';
  $real_field = 'tid';

  $industry_field = array();
  $v = taxonomy_vocabulary_machine_name_load("tm_segments");
  $terms = taxonomy_get_tree($v->vid, 0, 1); // get top level taxonomy
  foreach ($terms as $term) {
    // ie: $industry_field['846'] = 'Accommodation';
    $industry_field["tid_" . $term->tid] = $term->name;
  }

  $view->field["total_has_industry_pct"] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, "total_has_industry_pct", "Has " . $segment_label . " (%)");

  /* Count */
  foreach ($industry_field as $field_alias => $label) {
      $view->field[$field_alias] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, $field_alias, $label);  
  }

  /* Percentage */
  foreach ($industry_field as $field_alias => $label) {
      $field_alias .= '_pct';
      $label .= ' (%)'; 
      $view->field[$field_alias] = _tm_reports_add_handler_field_numeric($view, $table, $table_alias, $real_field, $field_alias, $label);        
  }

  // Fix Count for Industry Segment term
  foreach ($view->result as $i => $result) {

    // Step 1. count number of members with a segment
    $members_with_segment = 0;
    foreach ($industry_field as $field_alias => $label) {
      if (is_numeric($i) && (!empty($view->field[$field_alias]->view->result[$i]->$field_alias))) {
        $field_count = ($view->field[$field_alias]->view->result[$i]->field_count);
        $count = ($view->field[$field_alias]->view->result[$i]->$field_alias);
        $count_normalise = ($field_count != 0 ? $count / $field_count : $count);
        $members_with_segment += $count_normalise;     
      }
    }

    // correct field value. note: this is horrible code, but what can we do as we are wrangling with views :(
    $view->result[$i]->users_flagging__field_data_field_segment_field_segment_tid = $members_with_segment;

    // Step 2. Calculate % and update count
    foreach ($industry_field as $field_alias => $label) {
      if (is_numeric($i) && (!empty($view->field[$field_alias]->view->result[$i]->$field_alias))) {
        $field_count = ($view->field[$field_alias]->view->result[$i]->field_count);
        $count = ($view->field[$field_alias]->view->result[$i]->$field_alias);
        $count_normalise = ($field_count != 0 ? $count / $field_count : $count);
        $view->field[$field_alias]->view->result[$i]->$field_alias = $count_normalise;
          
        /* Percentage */
        $field_alias .= '_pct';
        //$total = $view->result[$i]->flag_counts_node_count;
        $pct = round(($count_normalise * 100 / $members_with_segment), 1);
        $view->field[$field_alias]->view->result[$i]->$field_alias = $pct;          
      }
    }

    // Step 3. Update total %
    //$approved_members = $view->field["total_has_industry_pct"]->view->result[$i]->total_has_industry_pct
    $approved_members = $view->result[$i]->flag_counts_node_count;
    $total_has_industry_pct = round($members_with_segment * 100 / $approved_members, 0);
    $view->field["total_has_industry_pct"]->view->result[$i]->total_has_industry_pct = $total_has_industry_pct;

  }
}

/**
* Helper function _tm_reports_add_handler_field_numeric
*/
function _tm_reports_add_handler_field_numeric(&$view, $table, $table_alias, $real_field, $field_alias, $label) {
  $field = new views_handler_field_numeric();
  $field ->field_alias =  $field_alias;
  $field ->aliases =  array();
  $field ->original_value =  NULL;
  $field ->additional_fields =  array();
  $field ->view =  &$view;
  $field ->query =  &$view->query;
  $field ->handler_type =  'field';
  $field ->table_alias =  $table_alias;
  $field ->real_field =  $real_field;
  $field ->relationship =  NULL;
  $field ->options = array(
    'id' => 'count',
    'table' => $table,
    'field' => 'count',
    'relationship' => $table_alias,
    'group_type' => 'group',
    'ui_name' => '',
    'label' => $label,
    'exclude' => FALSE,
    'alter'  => array(
      'alter_text' => FALSE,
      'text' => '',
      'make_link' => FALSE,
      'path' => '',
      'absolute' => FALSE,
      'external' => FALSE,
      'replace_spaces' => FALSE,
      'path_case' => 'none',
      'trim_whitespace' => FALSE,
      'alt' => '',
      'rel' => '',
      'link_class' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'nl2br' =>  FALSE,
      'max_length' => '',
      'word_boundary' =>  TRUE,
      'ellipsis' => TRUE,
      'more_link' => FALSE,
      'more_link_text' => '',
      'more_link_path' => '',
      'strip_tags' =>  FALSE,
      'trim' => FALSE,
      'preserve_tags' => '',
      'html' => FALSE,
    ),
    'element_type' => '',
    'element_class' => '',
    'element_label_type' => '',
    'element_label_class' => '',
    'element_label_colon' => TRUE,
    'element_wrapper_type' => '',
    'element_wrapper_class' => '',
    'element_default_classes' => TRUE,
    'empty' => '',
    'hide_empty' => FALSE,
    'empty_zero' => FALSE,
    'hide_alter_empty' => TRUE,
    'set_precision'  => FALSE,
    'precision' =>  0,
    'decimal' => '.',
    'separator' => ',',
    'format_plural' => FALSE,
    'format_plural_singular' => 1,
    'format_plural_plural' => '@count',
    'prefix' => '',
    'suffix' => '',
  );
  
  $field ->definition =  array(
    'handler' => 'views_handler_field_numeric',
    'click sortable' => TRUE,
    'group' => 'Field',
    'title' => $label,
    'help' => '',
  );
  
  $field ->is_handler =  TRUE;
  $field ->table =  $table;
  $field ->field =  $real_field;
  $field ->position = 0;
  
  return $field;
}

/**
 * Helper function _tm_reports_add_handler_field_numeric
 */
function _tm_reports_add_join_industry($field_alias, $tid) {
  $join = new views_join;
  $join->construct('taxonomy_term_hierarchy', 'users_flagging__field_data_field_segment', 'field_segment_tid', 'tid', array(), 'LEFT');
  $join->extra = array(
    array(
        'field' => 'tid',
        'value' => $tid,
    ),
    array(
        'field' => 'parent',
        'value' => $tid,
        'operator' => '=',
    ),
  );
  $join->extra_type = 'OR';
  return $join;
}

/**
 * Generate chapter stats for chapter leader 
 */
function tm_reports_chapter_insights($nid) {

  global $user;
  global $conf;
  $nid = _orig_nid();

  if($nid == 0) {
    print drupal_not_found();
    return;
  }

  $segment_label = "Industry Segment";
  if (isset($conf["tm_segment_label"])) {
    $segment_label = $conf["tm_segment_label"];
  }

  $flag_signup = flag_get_flag('signup', NULL);
  $flag_event_register = flag_get_flag('event_register', NULL);
  $flag_event_waitlist = flag_get_flag('event_waitlist', NULL);
  $flag_event_paid = flag_get_flag('event_paid', NULL);
  $chapter = node_load($nid);
  $return_link = l(t('View chapter'), url('node/'.$nid, array('absolute' => TRUE)));

  // Generate HTML
  $html = _tm_reports_insights_js_css_header();
  $redraw_functions = array("drawChart", "draw_insights_signups", "draw_insights_event_registrations", "draw_insights_event_waitlists", "draw_insights_event_payments", "draw_insights_event_registration_frequency", "insights_event_registration_frequency_aggregate");
  $html .= _tm_reports_insights_js_redraw_function($redraw_functions);

  // Start article
  $html .= "<article class='trilithon node view-mode-full node-by-viewer clearfix'>";

  // Insights
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>" . $chapter->title . " Insights &middot; <span style='color: #0068a8;'>" . $return_link . "</span></h1>
            </header>";
  $html .= _tm_reports_insights_table_html($chapter->nid);
  $html .= "</section>";

  // New Members
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>New Members - " . $chapter->title . "</h1>
            </header>";
  $html .= _tm_reports_insights_flagging_chart_html($chapter->nid, $flag_signup->fid, "", "New Members", "Month", "insights_signups");
  $html .= "</section>";

  // Event Registrations
  $chapter_event_nids = _tm_reports_get_chapter_event_nids($chapter->nid);

  // Show event charts if chapter has had events
  if (sizeof($chapter_event_nids) > 0) {

    $html .= "<section class='contained contained-block'>";
    $html .= "<header class='contained-head'>
              <h1 class='prime-title'>Event Registrations - " . $chapter->title . "</h1>
              </header>";
    $html .= _tm_reports_insights_flagging_chart_html($chapter_event_nids, $flag_event_register->fid, "", "Event Registrations", "Month", "insights_event_registrations");
    $html .= "</section>";

    // Event Waitlists
    // Only display is chapter has had waitlisted members
    $flag_event_waitlist = flag_get_flag('event_waitlist', NULL);
    $query = "SELECT COUNT(uid) AS amount FROM flagging WHERE entity_id IN (SELECT entity_id AS nid FROM field_data_field_chapter WHERE bundle = 'event' AND field_chapter_target_id = :chapter_id) AND fid = :fid";
    $num_event_waitlists = db_query($query, array(':fid' => $flag_event_waitlist->fid, ':chapter_id' => $chapter->nid))->fetch();
    if ($num_event_waitlists->amount > 0) {

      $insights["num_event_payments"] = $num_event_payments->amount;  

      $html .= "<section class='contained contained-block'>";
      $html .= "<header class='contained-head'>
                <h1 class='prime-title'>Event Waitlists - " . $chapter->title . "</h1>
                </header>";
      $html .= _tm_reports_insights_flagging_chart_html($chapter_event_nids, $flag_event_waitlist->fid, "", "Event Waitlists", "Month", "insights_event_waitlists");
      $html .= "</section>";

    }

    // Event Payments
    // Only display if payments have been made
    $query = "SELECT COUNT(uid) AS amount FROM flagging WHERE entity_id IN (SELECT entity_id AS nid FROM field_data_field_chapter WHERE bundle = 'event' AND field_chapter_target_id = :chapter_id) AND fid = :fid";
    $num_event_payments = db_query($query, array(':fid' => $flag_event_paid->fid, ':chapter_id' => $chapter->nid))->fetch();
    if ($num_event_payments->amount > 0) {

      $html .= "<section class='contained contained-block'>";
      $html .= "<header class='contained-head'>
                <h1 class='prime-title'>Event Payments - " . $chapter->title . "</h1>
                </header>";
      $html .= _tm_reports_insights_flagging_chart_html(_tm_reports_get_chapter_event_nids($chapter->nid), $flag_event_paid->fid, "", "Event Payments", "Month", "insights_event_payments");
      $html .= "</section>";
    }

    // Registration frequency
    $html .= "<section class='contained contained-block'>";
    $html .= "<header class='contained-head'>
              <h1 class='prime-title'>Number of Events Members Have Attended - " . $chapter->title . "</h1>
              </header>";
    $html .= _tm_reports_insights_event_registration_frequency_html($chapter->nid, true);
    $html .= "</section>";

  }

  // Industry Segments
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>" . $segment_label . " - " . $chapter->title . "</h1>
            </header>";
  $html .= _tm_reports_insights_segments_html($chapter->nid);
  $html .= "</section>";

  // Close article
  $html .= "</article>";

  // show tip?
  if (isset($conf["tm_reports_chapter_insights_tip"])) {
    $html .= "<style>.messages--status.messages { margin-left: 1rem; } </style>";
    drupal_set_message($conf["tm_reports_chapter_insights_tip"]);
  }

  $form['html'] =  array(
    '#type' => 'markup',
    '#markup' => $html);

  return $form;
}

/**
 * Generate global insights
 */
function tm_reports_global_insights() {

  global $user;
  global $conf;

  $segment_label = "Industry Segment";
  if (isset($conf["tm_segment_label"])) {
    $segment_label = $conf["tm_segment_label"];
  }

  $flag_signup = flag_get_flag('signup', NULL);
  //$return_link = l(t('Community Reports'), url('admin/tm_reports', array('absolute' => TRUE)));

  // Generate HTML
  $html = _tm_reports_insights_js_css_header();
  $redraw_functions = array("drawChart", "draw_new_signups", "draw_event_registrations", "draw_event_payments", "draw_follow_members", "draw_follow_organizations", "draw_monthly_chapters", "draw_status_updates", "draw_links_shared", "draw_insights_event_registration_frequency");
  $html .= _tm_reports_insights_js_redraw_function($redraw_functions);

  // Start artlce
  $html .= "<article class='trilithon node view-mode-full node-by-viewer clearfix'>";

  // Insights
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Global Insights</span></h1>"; // <!--&middot; <span style='color: #0068a8;'>" . $return_link . "</span></h1>
  $html .= "</header>";
  $html .= _tm_reports_insights_table_html();
  $html .= "</section>";

  // New Members
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>New Members</h1>
            </header>";
  $html .= _tm_reports_insights_all_signups_html();
  $html .= "</section>";

  // Event Registrations
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Event Registrations</h1>
            </header>";
  $html .= _tm_reports_insights_all_event_registrations_html();
  $html .= "</section>";

  // Event Payments
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Event Payments</h1>
            </header>";
  $html .= _tm_reports_insights_all_event_payments_html();
  $html .= "</section>";

  // Member Follows
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Member Connections</h1>
            </header>";
  $html .= _tm_reports_insights_all_member_connections_html();
  $html .= "</section>";

  // Organzation Follows
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Organization Connections</h1>
            </header>";
  $html .= _tm_reports_insights_all_organization_connections_html();
  $html .= "</section>";

  // New Chapters
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Total Chapters</h1>
            </header>";
  $html .= _tm_reports_insights_monthly_chapters_html();
  $html .= "</section>";

  // Status updates
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Status Updates</h1>
            </header>";
  $html .= _tm_reports_insights_monthly_status_updates_html();
  $html .= "</section>";

  // Links shared
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Links Shared</h1>
            </header>";
  $html .= _tm_reports_insights_monthly_links_shared_html();
  $html .= "</section>";

  // Registration frequency
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Number of Events Members Have Attended</h1>
            </header>";
  $html .= _tm_reports_insights_event_registration_frequency_html(null, true);
  $html .= "</section>";

  // Registration frequency
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>Number of Events Members Have Attended (Not Aggregated)</h1>
            </header>";
  $html .= _tm_reports_insights_event_registration_frequency_html(null, false);
  $html .= "</section>";

  // Segments
  $html .= "<section class='contained contained-block'>";
  $html .= "<header class='contained-head'>
            <h1 class='prime-title'>" . $segment_label . "</h1>
            </header>";
  $html .= _tm_reports_insights_segments_html();
  $html .= "</section>";

  // End article
  $html .= "</article>";

  $form['html'] =  array(
    '#type' => 'markup',
    '#markup' => $html);

  return $form;
}

/**
 * Generate a chart of flags on a node (ie: signups)
 */
function _tm_reports_insights_flagging_chart_html($node_id, $flag_id, $chart_title = "Flagging", $v_title = "Members", $h_title = "Month", $div_id = "insights_flagging") {

  // Step 1. Get chapter insight data
  $results = _tm_reports_flagging_time_series($node_id, $flag_id);

  // Step 2. Render chart
  $html = _tm_reports_insights_chart_html($results, $chart_title, $v_title, $h_title, $div_id);

  return $html;
}

/**
 * Generate a chart of all user signups
 */
function _tm_reports_insights_all_signups_html() {

  // Step 1. Get chapter insight data
  $results = _tm_reports_new_users_time_series();
  // Step 2. Render chart
  $html = _tm_reports_insights_chart_html($results, "", "New Members", "Month", "new_signups");
  return $html;
}

/**
 * Generate a chart of all event registrations
 */
function _tm_reports_insights_all_event_registrations_html() {

  $flag = flag_get_flag('event_register', NULL);
  // Step 1. Get chapter insight data
  $results = _tm_reports_flagging_time_series(NULL, $flag->fid, "node");
  // Step 2. Render chart
  $html = _tm_reports_insights_chart_html($results, "", "Event Registrations", "Month", "event_registrations");
  return $html;
}

/**
 * Generate a chart of all event payments
 */
function _tm_reports_insights_all_event_payments_html() {

  $flag = flag_get_flag('event_paid', NULL);
  // Step 1. Get chapter insight data
  $results = _tm_reports_flagging_time_series(NULL, $flag->fid, "node");
  // Step 2. Render chart
  $html = _tm_reports_insights_chart_html($results, "", "Event Payments", "Month", "event_payments");
  return $html;
}

/**
 * Generate a chart of all member follows
 */
function _tm_reports_insights_all_member_connections_html() {

  $flag = flag_get_flag('follow_members', NULL);
  // Step 1. Get chapter insight data
  $results = _tm_reports_flagging_time_series(NULL, $flag->fid, "user");
  // Step 2. Render chart
  $html = _tm_reports_insights_chart_html($results, "", "Follow Members", "Month", "follow_members");
  return $html;
}

/**
 * Generate a chart of all organisation follows
 */
function _tm_reports_insights_all_organization_connections_html() {

  $flag = flag_get_flag('follow_organizations', NULL);
  // Step 1. Get chapter insight data
  $results = _tm_reports_flagging_time_series(NULL, $flag->fid, "node");
  // Step 2. Render chart
  $html = _tm_reports_insights_chart_html($results, "", "Follow Organization", "Month", "follow_organizations");
  return $html;
}

/**
 * Generate a chart of number of chapters over time
 */
function _tm_reports_insights_monthly_chapters_html() {

  // Step 1. Get chapter insight data
  $results = _tm_reports_monthly_chapters_time_series("INTERVAL 1 YEAR");
  // Step 2. Render chart
  $html = _tm_reports_insights_chart_html($results, "", "Total Chapters", "Month", "monthly_chapters");
  return $html;
}

/**
 * Generate a chart of status updates per month
 */
function _tm_reports_insights_monthly_status_updates_html() {

  // Step 1. Get status update data
  $results = _tm_reports_status_updates_time_series("INTERVAL 1 YEAR");
  // Step 2. Render chart
  $html = _tm_reports_insights_chart_html($results, "", "Status Updates", "Month", "status_updates");
  return $html;
}

/**
 * Generate a chart of links shared per month
 */
function _tm_reports_insights_monthly_links_shared_html() {

  // Step 1. Get status update data
  $results = _tm_reports_links_shared_time_series("INTERVAL 1 YEAR");
  // Step 2. Render chart
  $html = _tm_reports_insights_chart_html($results, "", "Links Shared", "Month", "links_shared");
  return $html;
}

/**
 * Generate a chart of frequency of events for attendees
 */
function _tm_reports_insights_event_registration_frequency_html($chapter_id = null, $aggregate = false) {

  // Step 1. Get status update data
  $results = _tm_reports_event_registration_frequency($chapter_id, $aggregate);
  // Step 2. Render chart
  $js_fn = "insights_event_registration_frequency";
  if ($aggregate) {
    $js_fn = "insights_event_registration_frequency_aggregate";
  }
  $html = _tm_reports_insights_chart_html($results, "", "Members", "Number of Events", $js_fn);
  return $html;
}


/**
 * Generate Google Chart from a data series
 */
function _tm_reports_insights_chart_html($results, $chart_title, $v_title, $h_title, $div_id) {

  // Format in Google chart
  $html = "<script>";

  $html .= "\ngoogle.setOnLoadCallback(draw_" . $div_id . ");";
  $html .= "\nfunction draw_" . $div_id . "() {";
  $html .= "\nvar data = new google.visualization.DataTable();";
  $html .= "\ndata.addColumn('string', '" . $h_title . "');";
  $html .= "\ndata.addColumn('number', '" . $v_title . "');";

  $html .= "data.addRows([";

  foreach ($results as $result) {
    if (isset($result["label"])) {
      $html .= "['" . $result["label"] . "', " . $result["total"] . "],";
    } else {
      $html .= "['" . $result["group_year"] . "-" . $result["group_month"] . "', " . $result["total"] . "],";
    }
  }

  $html .= <<<EOT
      ]);
EOT;

  $html .= "
      var options = {
        title: '" . $chart_title . "',
        hAxis: {
          title: '" . $h_title . "',
        },
        vAxis: {
          title: '" . $v_title . "'
        },
        legend: { position: 'none' },
      };";

  $html .= "\nvar chart = new google.visualization.ColumnChart(document.getElementById('" . $div_id . "'));";
  $html .= "\nchart.draw(data, options);";
  $html .= "\n}";
  $html .= "\n</script>";
  $html .= '<div id="' . $div_id . '" style="width: 100%; height: 400px;"></div>';

  return $html;
}

/**
 * Load Google Chart API via JS
 */
function _tm_reports_insights_js_css_header() {

  // Html to load Google chart data
  $html = <<<EOT
<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<script type='text/javascript'>
// load google charts
google.load('visualization', '1.1', {packages:['corechart', 'table', 'bar']});

// hide drupal title
document.getElementById("page-title").style.display = 'none';
</script>
<style>
.google-visualization-table-tr-head { display: none; }
</style>
EOT;

  return $html;
}
 
/*
 * Generate js redraw listener code to resize charts/graphs on window resize
 */
function _tm_reports_insights_js_redraw_function($redraw_functions) {

  $html = "<script>\n";

  $html .= "window.onresize = function(e) {
  delay(function(){";

  foreach ($redraw_functions as $fn) {
    $html .= "\nif (typeof " . $fn . " == 'function') { " . $fn . "(); }";
  }
  
  $html .= "}, 250); 
}

var delay = (function(){
  var timer = 0;
  return function(callback, ms){
    clearTimeout (timer);
    timer = setTimeout(callback, ms);
  };
})();

</script>";

  return $html;
}

/**
 * Generate Chapter/Global Insights Table via Google Charts
 */
function _tm_reports_insights_table_html($chapter_id = "") {

  // Step 1. Get chapter insight data or global data
  if ($chapter_id == "") {
    $data = _tm_reports_get_global_insights();
  } else {
    $data = _tm_reports_get_chapter_insights($chapter_id);
  }
  $chapter_insights = $data["data_values"];
  $data_labels = $data["data_labels"];

  // Step 2. Format in Google chart
  $html = <<<EOT
<script>
google.setOnLoadCallback(drawTable);
function drawTable() {
  var data = new google.visualization.DataTable();
  data.addColumn('string', 'Description');
  data.addColumn('string', 'Value');
  data.addRows([
EOT;

  $hide_values = [];
  if ($chapter_id != "") {
    $hide_values = ["members_approved_with_segment", "members_approved_without_segment", "members_unapproved_total"];
  }
  foreach ($chapter_insights as $key => $value) {
    if (!in_array($key, $hide_values)) {
      if ($data_labels[$key][0] == "%") {
        $html .= "['" . $data_labels[$key] . "', '" . $value . "%'],";
      } else {
        $html .= "['" . $data_labels[$key] . "', '" . $value . "'],";
      }
    }
  }

  $html .= <<<EOT
  ]);

  var table = new google.visualization.Table(document.getElementById('insights_table'));
  table.draw(data, {showRowNumber: false, sort: false, width: '100%'});
}
</script>
<div id="insights_table" style="width: 100%;"></div>
EOT;

  return $html;
}

/**
 * Get Industry Segment Data from a chapter or global (approved members)
 * Note: CACHED
 */
function _tm_reports_get_industry_segment_data($chapter_id = "") {

  // check cache
  $cache = cache_get('tm-reports-get-industry-segment-data-' . $chapter_id, 'cache');
  if (!empty($cache)) {
    return $cache->data;
  }

  $approved_role = user_role_load_by_name("approved user");

  // SQL - Join to Chapter
  if ($chapter_id != "") {
    $chapter = node_load($chapter_id);
    $flag = flag_get_flag('signup', NULL);
    
    $query = "select count(users.uid) as total, taxonomy_term_data.tid as segment_tid, taxonomy_term_data.name from users
  left join flagging on users.uid = flagging.uid
  left join field_data_field_segment on users.uid = field_data_field_segment.entity_id
  left join taxonomy_term_hierarchy on taxonomy_term_hierarchy.tid = field_data_field_segment.field_segment_tid 
  left join taxonomy_term_data ON (IF (taxonomy_term_hierarchy.parent > 0, taxonomy_term_hierarchy.parent, taxonomy_term_hierarchy.tid) = taxonomy_term_data.tid)
  left join users_roles ON users_roles.uid = users.uid 
  where users_roles.rid = :role_id
  and fid = :fid
  and flagging.entity_id = :chapter_nid
  and flagging.entity_type = 'node'
  and field_data_field_segment.entity_type = 'user'
  and taxonomy_term_data.tid is not null
  group by segment_tid
  order by name";

    $rows = db_query($query, array(':fid' => $flag->fid, ':role_id' => $approved_role->rid, ':chapter_nid' => $chapter->nid))->fetchAll();

  } else {
    // SQL - Global
    $query = "select count(users.uid) as total, taxonomy_term_data.tid as segment_tid, taxonomy_term_data.name from users
  left join field_data_field_segment on users.uid = field_data_field_segment.entity_id
  left join taxonomy_term_hierarchy on taxonomy_term_hierarchy.tid = field_data_field_segment.field_segment_tid 
  left join taxonomy_term_data ON (IF (taxonomy_term_hierarchy.parent > 0, taxonomy_term_hierarchy.parent, taxonomy_term_hierarchy.tid) = taxonomy_term_data.tid)
  left join users_roles ON users_roles.uid = users.uid 
  where users_roles.rid = :role_id
  and field_data_field_segment.entity_type = 'user'
  and taxonomy_term_data.tid is not null
  group by segment_tid
  order by name";

    $rows = db_query($query, array(':role_id' => $approved_role->rid))->fetchAll();

  }
  
  // Prepare row data
  $segment_data = array();
  foreach ($rows as $row) {
    $segment_data[] = array("name" => $row->name, "total" => $row->total, "tid" => $row->segment_tid);
  }

  // RETURN DATA
  $data_labels = tm_reports_get_insights_labels();
  cache_set('tm-reports-get-industry-segment-data-' . $chapter_id, $segment_data, 'cache', time() + 900); // 15 mins
  return $segment_data;
}

/**
 * Get monthly flagging data for a node and flag over time
 * Note: CACHED
 */
function _tm_reports_flagging_time_series($node_id, $flag_id, $entity_type = "node", $timestamp_interval = "INTERVAL 1 YEAR") {

  // check cache
  if (is_array($node_id)) {
    $cache_key_node_id = implode("_", $node_id);
  } else {
    $cache_key_node_id = $node_id;
  }
  $cache_key = "tm-reports-flagging-time-series-" . $cache_key_node_id . "-" . $flag_id . "-" . $entity_type . "-" . $timestamp_interval;
  $cache_key = str_replace(" ", "-", $cache_key);
  $cache = cache_get($cache_key, 'cache');
  if (!empty($cache)) {
    return $cache->data;
  }

  // SQL 
  $query = "select count(*) as total, YEAR(FROM_UNIXTIME(timestamp)) as group_year, MONTH(FROM_UNIXTIME(timestamp)) as group_month from flagging
  where FROM_UNIXTIME(timestamp) >= DATE_SUB(NOW()," . $timestamp_interval . ")";

  // node_id can be null, id, or array
  if ((is_array($node_id) and sizeof($node_id) > 0)) {
    $query .= " and entity_id IN (:node_id)"; 
  } else if ($node_id != NULL) {
    $query .= " and entity_id = :node_id"; 
  }
  
  $query .= " and fid = :fid
  and entity_type = :entity_type
  group by group_year, group_month order by group_year, group_month asc;";

  $params = array(':node_id' => $node_id, ':fid' => $flag_id, ':entity_type' => $entity_type);
  if ($node_id == NULL) {
    $params = array(':fid' => $flag_id, ':entity_type' => $entity_type);
  }

  $rows = db_query($query, $params)->fetchAll();

  // pad the grouped data data
  $series = _tm_reports_helper_pad_monthly_grouped_data($rows);

  // return data
  cache_set($cache_key, $series, 'cache', time() + 900); // 15 mins
  return $series;
}

/**
 * Get monthly new user signup data over time
 */
function _tm_reports_new_users_time_series($timestamp_interval = "INTERVAL 1 YEAR") {

   // check cache
  $cache_key = "tm-reports-new-users-" . $timestamp_interval;
  $cache_key = str_replace(" ", "-", $cache_key);
  $cache = cache_get($cache_key, 'cache');
  if (!empty($cache)) {
    return $cache->data;
  }

  // SQL 
  $query = "select count(*) as total, YEAR(FROM_UNIXTIME(created)) as group_year, MONTH(FROM_UNIXTIME(created)) as group_month from users
  where FROM_UNIXTIME(created) >= DATE_SUB(NOW()," . $timestamp_interval . ")
  group by group_year, group_month order by group_year, group_month asc;";
  
  $rows = db_query($query)->fetchAll();

  // pad the grouped data data
  $series = _tm_reports_helper_pad_monthly_grouped_data($rows);

  // return data
  cache_set($cache_key, $series, 'cache', time() + 900); // 15 mins
  return $series;
}

/**
 * Get total chapters over time
 */
function _tm_reports_monthly_chapters_time_series($timestamp_interval = "INTERVAL 1 YEAR") {

   // check cache
  $cache_key = "tm-reports-monthly-chapters-" . $timestamp_interval;
  $cache_key = str_replace(" ", "-", $cache_key);
  $cache = cache_get($cache_key, 'cache');
  if (!empty($cache)) {
    return $cache->data;
  } 

  // SQL 
  $query = "select count(*) as total, YEAR(FROM_UNIXTIME(created)) as group_year, MONTH(FROM_UNIXTIME(created)) as group_month from node
  where type = 'chapter' and status = 1 
  and FROM_UNIXTIME(created) >= DATE_SUB(NOW()," . $timestamp_interval . ")
  group by group_year, group_month order by group_year, group_month asc;";
  
  $rows = db_query($query)->fetchAll();

  // pad the grouped data data
  $series = _tm_reports_helper_pad_monthly_grouped_data($rows);

  // calculate series total
  $series_total = 0;
  for ($i = 0; $i < sizeof($series); $i++) {
    $series_total = $series_total + $series[$i]["total"];
  }

  // get total number of chapters
  $query = "SELECT COUNT(*) amount FROM {node} n ".
              "WHERE n.type = :type";
  $num_chapters = db_query($query, array(':type' => "chapter"))->fetch()->amount;

  // starting total
  $total = $num_chapters - $series_total;

  // aggregate monthly totals
  for ($i = 0; $i < sizeof($series); $i++) {
    $total = $series[$i]["total"] + $total;
    $series[$i]["total"] = $total;
  }

  // return data
  cache_set($cache_key, $series, 'cache', time() + 300); // 5 mins
  return $series;
}

/**
 * Get monthly status updates data over time
 */
function _tm_reports_status_updates_time_series($timestamp_interval = "INTERVAL 1 YEAR") {

   // check cache
  $cache_key = "tm-reports-status-updates-" . $timestamp_interval;
  $cache_key = str_replace(" ", "-", $cache_key);
  $cache = cache_get($cache_key, 'cache');
  if (!empty($cache)) {
    return $cache->data;
  }

  // SQL 
  $query = "select count(*) as total, YEAR(created) as group_year, MONTH(created) as group_month from tm_newsfeed_status_updates
  where is_removed = 0 and created >= DATE_SUB(NOW()," . $timestamp_interval . ")
  group by group_year, group_month order by group_year, group_month asc;";
  
  $rows = db_query($query)->fetchAll();

  // pad the grouped data data
  $series = _tm_reports_helper_pad_monthly_grouped_data($rows);

  // return data
  cache_set($cache_key, $series, 'cache', time() + 900); // 15 mins
  return $series;
}

/**
 * Get preview links shared over time
 */
function _tm_reports_links_shared_time_series($timestamp_interval = "INTERVAL 1 YEAR") {

   // check cache
  $cache_key = "tm-reports-links-shared-" . $timestamp_interval;
  $cache_key = str_replace(" ", "-", $cache_key);
  $cache = cache_get($cache_key, 'cache');
  if (!empty($cache)) {
    return $cache->data;
  }

  // SQL 
  $query = "select count(*) as total, YEAR(created) as group_year, MONTH(created) as group_month from tm_newsfeed_status_updates
  where is_removed = 0 and preview_link_id is not null and created >= DATE_SUB(NOW()," . $timestamp_interval . ")
  group by group_year, group_month order by group_year, group_month asc;";
  
  $rows = db_query($query)->fetchAll();

  // pad the grouped data data
  $series = _tm_reports_helper_pad_monthly_grouped_data($rows);

  // return data
  cache_set($cache_key, $series, 'cache', time() + 900); // 15 mins
  return $series;
}

/**
 * Helper method to pad empty sql grouped data in a time series
 */
function _tm_reports_helper_pad_monthly_grouped_data($rows) {

  // Step 1. Create a keyed array
  // key in array as as YYYY_MM
  $results = array();
  foreach ($rows as $row) {
    $results[$row->group_year . "_" . $row->group_month] = array("total" => $row->total, "group_year" => $row->group_year, "group_month" => $row->group_month);
  }

  // Step 2. Pad results for with no entries
  $start_year = 2014;
  $start_month = 1;
  $series = array();
  $started_data = false;
  $at_current_month = false;
  for ($i=$start_year; $i <= intval(date("Y")); $i++) {
    for ($j=$start_month; (($j <= 12) && !$at_current_month); $j++) { 

      // check if we are at current month
      $at_current_month = ($i == intval(date("Y")) && ($j == intval(date("n"))));

      $key = $i . "_" . $j;
      if (array_key_exists($key, $results)) {
        $started_data = true;
        $series[] = $results[$key]; // add existing data
      } else if ($started_data) {
        // pad data
        $series[] = array("total" => 0, "group_year" => $i, "group_month" => $j);
      }
    }
  }

  return $series;
}

/**
 * Get event attendance frequency
 */
function _tm_reports_event_registration_frequency($chapter_id = null, $aggregate = false) {

  // check cache
  $cache_key = "tm-reports-event-registration-frequency-" . $chapter_id . "-" . $aggregate;
  $cache_key = str_replace(" ", "-", $cache_key);
  $cache = cache_get($cache_key, 'cache');
  if (!empty($cache)) {
    return $cache->data;
  }

  // SQL
  $flag_event_register = flag_get_flag('event_register', NULL);
  if ($chapter_id == null) {
    $query = "SELECT amount, COUNT(*) AS freq FROM (SELECT uid, COUNT(uid) AS amount FROM flagging f WHERE f.fid = :fid group by uid) AS t2 GROUP BY amount ORDER BY amount ASC";
    $rows = db_query($query, array(":fid" => $flag_event_register->fid) )->fetchAll();
  } else {
    $query = "SELECT amount, COUNT(*) AS freq FROM (SELECT uid, COUNT(uid) AS amount FROM flagging f WHERE entity_id IN (SELECT entity_id AS nid FROM field_data_field_chapter WHERE bundle = 'event' AND field_chapter_target_id = :chapter_id) AND f.fid = :fid GROUP BY uid) as t2 GROUP BY amount ORDER BY amount ASC";
    $rows = db_query($query, array(":chapter_id" => $chapter_id, ":fid" => $flag_event_register->fid) )->fetchAll();
  }

  // pad the grouped data data
  $series = array();
  $max_amount = 10;
  $max_total = 0;
  foreach ($rows as $row) {
    if ($row->amount >= $max_amount) {
      $max_total = $max_total + $row->freq;
    } else {
      $series[$row->amount] = array("label" => $row->amount, "total" => $row->freq);
    }
  }
  
  // add max amount
  $series[$max_amount] = array("label" => $max_amount . "+", "total" => $max_total);

  // pad empty groups
  for ($i = 1; $i <= $max_amount; $i++) {
    if (!isset($series[$i])) {
      $series[$i] = array("label" => $i, "total" => 0);
    }
  }

  // aggregate 2+ events
  // ie: 1 event, 2 or more, 3 or more
  if ($aggregate) {
    $aggregate = 0;
    for ($i = $max_amount; $i >= 2; $i--) {
      $aggregate = $aggregate + $series[$i]["total"];
      $series[$i] = array("label" => $i . "+", "total" => $aggregate);
    }
  }

  // sort it
  ksort($series);

  // return data
  cache_set($cache_key, $series, 'cache', time() + 900); // 15 mins
  return $series;
}

/**
 * Generate Chapter / Global Segments Pie Chart via Google Charts
 */
function _tm_reports_insights_segments_html($chapter_id = "") {

  // // Step 1. Get segment data
  $segment_data = _tm_reports_get_industry_segment_data($chapter_id);

  // Step 2. Format in Google chart
  $html = <<<EOT

<script>
google.setOnLoadCallback(drawChart);
function drawChart() {
  var data = google.visualization.arrayToDataTable([
  ['Segment', 'Members'],
EOT;

  foreach ($segment_data as $segment) {
    $html .= "['" . str_replace("'", "", $segment["name"]) . "'," . $segment["total"] . "],";
  }
  $html .= <<<EOT
  ]);

EOT;
  
  // Report chart colors
  // If ?reports_color_hash is provided, create a unique color code for each segment
  // This is so segment colors are consistent across all graphs regardless of order in the chart
  // ie: 0: { color: '#014eff' },
  // ie: 1: { color: '#ab6754' }
  // default is off
  $color_hash = null;

  // get from cookie
  if (isset($_COOKIE['Drupal_visitor_tm_reports_color_hash'])) {
   $color_hash = $_COOKIE['Drupal_visitor_tm_reports_color_hash'];
  }

  // ie: 
  // ?chart_color_hash
  // ?chart_color_hash = 123
  if (isset($_GET["reports_color_hash"])) {
    $color_hash = $_GET["reports_color_hash"];
    if ($color_hash == "") {
      $color_hash = null;
    }
    user_cookie_save(array("tm_reports_color_hash" => $color_hash));
  }

  if ($color_hash != null) {
    $count = 0;
    $color_parts = array();
    foreach ($segment_data as $segment) {
      $color_parts[] = $count++ . ": { color: '#" . _tm_reports_string_color_code($segment["name"] . $color_hash) . "' }";
    }
    $html .= "var slices = {" . implode(", ", $color_parts) . "};";
  } else {
    $html .= "var slices = {};";
  }

  $random_number = rand(0,1000);
  $html .= <<<EOT
  var options = { 'slices': slices };
  var chart = new google.visualization.PieChart(document.getElementById('insights_segments'));
  chart.draw(data, options);
}
</script>
<div id="insights_segments" style="width: 100%; height: 700px;"></div>
<div style='padding: 8px; text-align: right;'><a href='?reports_color_hash={$random_number}'>Randomize chart color</a> | <a href='?reports_color_hash='>Reset</a></div>
EOT;

  return $html;
}

/**
 * Helper method to convert string to color code
 */
function _tm_reports_string_color_code($str) {
  // ref: http://stackoverflow.com/questions/3724111/how-can-i-convert-strings-to-an-html-color-code-hash
  $code = dechex(crc32($str));
  $code = substr($code, 0, 6);
  return $code;
}

/**
 * Get all event nids for a chapter (does not include published events)
 */
function _tm_reports_get_chapter_event_nids($chapter_id) {

  $event_nids = array();
  $query = "SELECT entity_id AS nid FROM field_data_field_chapter WHERE bundle = 'event' AND field_chapter_target_id = :chapter_id";
  $results = db_query($query, array(':chapter_id' => $chapter_id))->fetchAll();
  foreach ($results as $result) {
    $event_nids[] = $result->nid;
  }
  return $event_nids;
}

