<?php
/**
 * @file
 * Code for the TM Event signup feature.
 * 
 * @author Daniel da Silva (daniel.silva@flipside.org)
 */

include_once 'tm_event_signup.features.inc';

/**
 * Implement hook_ds_field_info()
 */
function tm_event_signup_ds_fields_info($entity_type) {
  if ($entity_type != 'node') {
    return;
  }
  $fields = array();
  
  $fields['tm_ds_event_seats_count'] = array(
    'title' => t('Seats Available'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('event|*'),
    'function' => '_tm_event_seats_count'
  );

  return array($entity_type => $fields);
}

/**
 * Custom function to get the seats count.
 * Todo: Refactor this some day.
 */
function _tm_event_seats_count($field, $title = NULL) {

  global $conf;

  $event = $field['entity'];
  $flag = flag_get_flag('event_register');

  // External event check  
  $display_external = (isset($event->field_external_rsvp[LANGUAGE_NONE][0]['value']) && $event->field_external_rsvp[LANGUAGE_NONE][0]['value'] !== '0');

  // Registered count
  $count = $flag->get_count($event->nid);
  $registered_count = $count; // keep track of registered count

  // Extra stuff. Add non-registered guests to count
  $extra_guests_count = 0;
  if (isset($event->field_event_extra_guests[LANGUAGE_NONE][0]['value'])) {
    $extra_guests_count = $event->field_event_extra_guests[LANGUAGE_NONE][0]['value'];
    $count = $count + $extra_guests_count;
  }

  // Past event
  if (_tm_event_is_past($event)) {
    
    // Extra stuff. Show total attendance
    if (isset($event->field_event_total_attendance[LANGUAGE_NONE][0]['value'])) {
      $total_attendance = $event->field_event_total_attendance[LANGUAGE_NONE][0]['value'];
      return t($total_attendance . " people went");
    }

    // RSVP event without total attenance
    if ($display_external) {
      return t('Past event');
    }

    // Nobody came, wtf? :(
    if ($count == 0) {
      return t("Past event");
    }

    // Lonely event :(
    if ($count == 1) {
      return t("1 person went");
    }

    // No total attendance specified
    return t($count . " people went");
  }
  
  // Future event...
  if ($display_external) {
    return t('Please RSVP For This Event');
  }

  // Nobody registered yet
  if ($count == 0) {

    // Hide count message if event is ticketed
    if (module_exists("tm_payments")) {
      if (_tm_payments_is_payment_enabled($event)) {
        return t('Buy a ticket to this event');
      }
    }

    // Seats limited
    if (isset($event->field_signup_limit[LANGUAGE_NONE][0]['value'])) {
      $limit = $event->field_signup_limit[LANGUAGE_NONE][0]['value'];
      $waitlist_flag = flag_get_flag('event_waitlist');
      $waitlist_count = $waitlist_flag->get_count($event->nid);
      if (($limit == 0) && ($waitlist_count == 0)) {
        // event it set to waitlist all attendees
        return t('This is a waitlisted event');
      } else {
        if ($waitlist_count == 0) {
          return t('Be the first to register!');
        }
        return t($waitlist_count . ' on the waitlist');
      }
    } else {
      return t('Be the first to register!');
    }
  }
  
  // Show how many peoplare going
  $count_text = "people are going";
  if ($count == 1) {
    $count_text = "person is going";
  }

  // If signup limit, show seats left
  if (isset($event->field_signup_limit[LANGUAGE_NONE][0]['value'])) {
    $limit = $event->field_signup_limit[LANGUAGE_NONE][0]['value'];
    
    // Seats left.
    $left = $limit - $registered_count;
    $left = $left < 0 ? 0 : $left;

    $left_text = "spots left";
    if ($left == 1) {
      $left_text = "spot left";
    }

    if ($left == 0) {
      $waitlist_flag = flag_get_flag('event_waitlist');
      $waitlist_count = $waitlist_flag->get_count($event->nid);
      if ($waitlist_count > 0) {
        if ($count == 0) {
          // ie: 5 people on the waitlist
          return t($waitlist_count . ' on the waitlist.<br>');
        } else {
          // ie: 5 people are going, 3 on waitlist
          return t($count . ' ' . $count_text . '<br>' . $waitlist_count . ' on the waitlist<br>');
        }
      } else {
        return t($count . ' ' . $count_text . '<br>This event is full<br>');
      }
    }
    
    // show x people going
    $show_text = $count . ' ' . $count_text;

    // show spots
    $tm_event_show_spots_left = 0;
    if (isset($conf['tm_event_show_spots_left'])) {
      $tm_event_show_spots_left = $conf['tm_event_show_spots_left'];
    }
    // if below threshold, show spots
    if (($left <= $tm_event_show_spots_left) or ($tm_event_show_spots_left == 0)) {
      $show_text .= '<br>' . $left . ' ' . $left_text;
    }

    return t($show_text);
  }

  // No signup limit, must say how many people are going
  $show_text = $count . ' ' . $count_text;

  // A few people are going
  if (($show_text == "1 person is going") or ($show_text == "2 people are going") or ($show_text == "3 people are going")) {
    $show_text = "A few people are going";
  }
  
  return t($show_text);
}

/**
 * Implements hook_flag_validate()
 * When flagging an entity with the signup flag, check if the
 * signup limit was reached.
 */
function tm_event_signup_flag_validate($action, $flag, $entity_id, $account, $skip_permission_check, $flagging) {

  // skip if permission check set
  if ($skip_permission_check) {
    return;
  }

  // get flagged entity
  $flagged_entity = node_load($entity_id);

  // Only validate the 'signup' flag whenever an 'event' is flagged. Users may always unflag.
  if ($flag->name == 'event_register' && $action == 'flag' && $flagged_entity->type == 'event') {
    $result = _tm_event_display_flag($entity_id);

    // Check if added by moderator in tm_events_moderation_events_register_member()
    $static_register_member_moderator = &drupal_static("tm_register_member_moderator");
    $is_added_by_moderator = ($static_register_member_moderator != null);

    if (($result == "show_waitlist") and (!$is_added_by_moderator)) {
      drupal_set_message("Sorry, this event is now full.", "warning");
      drupal_goto("node/" . $entity_id);
      return(array('access-denied' => t('Sorry, the signup limit reached.')));
    }
  }
}

/**
 * Implements hook_flag_javascript_info_alter()
 * Used to add fields to the javascript response, like the errors and
 * an updated flag count.
 */
function tm_event_signup_flag_javascript_info_alter(&$info, $flag) {
  if ($flag->name === 'event_register') {
    $info['errors'] = $flag->get_errors();
    
    // Shortcut.
    $nid = $info['contentId'];
    $event = node_load($nid);
    
    if (isset($event->field_signup_limit[LANGUAGE_NONE][0]['value'])) {
      $limit = $event->field_signup_limit[LANGUAGE_NONE][0]['value'];
      $count = $flag->get_count($nid);
      
      // Seats left.
      $left = $limit - $count;
      $left = $left < 0 ? 0 : $left;
      
      // Variables needed to theme the seats count.
      $info['updatedSeatsLeft'] = $left;
      $info['totalSeats'] = $limit;
    }
    
    // Re-render the links without the error messages.
    // The messages are stored in the "errors" key and should be handled
    // on the javascript side.
    //$info['newLink'] = $flag->theme($flag->is_flagged($nid) ? 'unflag' : 'flag', $nid);
  }
}

/**
 * Implements hook_preprocess_flag()
 * Preprocess the register and waitlist flags to display or hide them
 */
function tm_event_signup_preprocess_flag(&$variables) {
  
  // Shortcuts.
  $flag = $variables['flag'];
  $status = $variables['status']; // set in _tm_flags_flag_limits()
  $event_id = $variables['entity_id'];
  $variables['event_id'] = $event_id;

  // Check flag
  if (($flag->name != "event_register") and ($flag->name != "event_waitlist")) {
    return;
  }

  // Check flagged entity
  $flagged_entity = node_load($event_id);
  if (!isset($flagged_entity->type)) {
    return;
  }

  // Must be event
  if ($flagged_entity->type != 'event') {
    return;
  }

  // The register flag may be hidden but also send through variables to flag.tpl.php to
  // indicate whether to show closed event, external_rsvp, etc.
  // ie: show_closed, show_external_rsvp, show_register, show_waitlist, or show_not_approved
  $event_flag = _tm_event_display_flag($event_id);
  $variables['event_flag'] = $event_flag;

  // Hide register flag if on waitlist, or external rsvp
  if ($flag->name == "event_register") {
     if (($event_flag == "show_waitlist") or ($event_flag == "show_external_rsvp")) {
      $variables['do_not_display_flag'] = true;
    }
  }

  // Hide waitlist flag if not showing waitlist
  if ($flag->name == "event_waitlist") {
    if ($event_flag != "show_waitlist") {
      $variables['do_not_display_flag'] = true;
    }
  }

}

/**
 * Checks if the current user can join the event with the given nid.
 * In order to signup, the signup limit can't be reached and the event
 * can't be in the past.
 * 
 * returns show_closed, show_external_rsvp, show_register, show_waitlist, or show_not_approved
 * 
 * @param $nid
 *   The event id
 */
function _tm_event_display_flag($nid, $account = null) {

  global $user;

  // check for a different account
  if ($account == null) {
    $account = $user;
  }

  // Flags
  $flag_register = flag_get_flag('event_register');
  $flag_waitlist = flag_get_flag('event_waitlist');

  $limit = 0;
  $event = node_load($nid);

  if (!$event || $event->type != 'event') {
    throw new Exception("Invalid event node. Nid: " . $nid);
  } 

  // Is past event
  $is_past_event = _tm_event_is_past($event);

  // Payment type
  $payment_type = "no_payment";
  if (module_exists("tm_payments")) {
	  $payment_type = _tm_payments_get_payment_type($event);
  }
  
  // Check if is external RSVP.
  // Is external event
  $display_external = (isset($event->field_external_rsvp[LANGUAGE_NONE][0]['value']) && $event->field_external_rsvp[LANGUAGE_NONE][0]['value'] !== '0');

  // External rsvp and past event
  if ($is_past_event and $display_external) {
    return 'show_external_rsvp_closed';
  }

  // External rsvp
  if ($display_external) {
    return 'show_external_rsvp';
  }

  // If logged out, and payments enabled, show ticket
  if ($account->uid == 0) {
    if (module_exists("tm_payments")) {
      if (_tm_payments_is_payment_enabled($event)) {
        // if past event, check if field_event_payment_post_event enabled
        if (_tm_event_is_past($event)) {
          if (isset($event->field_event_payment_post_event[LANGUAGE_NONE][0]['value'])) {
            $payment_post_event = $event->field_event_payment_post_event[LANGUAGE_NONE][0]['value'];
            if ($payment_post_event) {
              return 'show_checkout';
            }
          }
          return 'show_closed';
        }

        // future event
        return 'show_checkout';
      }
    }
  }

  // Show donation if user is registered for event, but has not paid
  if (module_exists("tm_payments")) {
    if (_tm_payments_is_payment_enabled($event)) {
      if (tm_events_user_is_registered($event->nid, $account->uid)) { 
        if ((!_tm_payments_user_has_paid($event->nid, $account->uid)) and ($payment_type != "fixed_price")) {
          if ($is_past_event) {
            $payment_post_event = $event->field_event_payment_post_event[LANGUAGE_NONE][0]['value'];
            if ($payment_post_event) {
              return 'show_donate';
            }
          } else {
            return 'show_donate';
          }
        }      
      }
    }
  }

  // Show feedback for recent chapter events user has registered for
  if ($is_past_event) {
    if (module_exists("tm_nps")) {
      if (tm_events_user_is_registered($event->nid, $account->uid)) {
        if (isset($event->field_chapter[LANGUAGE_NONE][0]['target_id'])) {
          $seconds_since_event = 7 * 24 * 60 * 60;
          if (tm_events_seconds_until_event_starts($event) > (-$seconds_since_event)) {
            return 'show_feedback';
          }
        }
      }
    }
  }

  // Is waitlisted
  $is_waitlisted = $flag_waitlist->is_flagged($nid, $account->uid);
  if ($is_waitlisted) {
    if ($is_past_event) {
      return 'show_closed';
    }
    return 'show_waitlist';
  }

  // If already registered
  if ($flag_register->is_flagged($nid, $account->uid)) {
      return 'show_register';
  }

  // Check if we are approved
  $approved_members_only = $event->field_approved_members_only[LANGUAGE_NONE][0]['value'];
  $approved_member = in_array("approved user", $account->roles);
  if ($approved_members_only and !$approved_member) {
    if ($is_past_event) {
      return 'show_closed';
    }
    return 'show_not_approved';
  }

  // Check event geoblock settings 
  $check_user = user_load($account->uid);
  if (!tm_events_check_geoblock_signup($check_user, $event)) {
    if ($is_past_event) {
      return 'show_closed';
    }
    return 'show_geoblocked';
  }

  // Check signup limit
  if (isset($event->field_signup_limit[LANGUAGE_NONE][0]['value'])) {

    // Get signup limit
    $limit = trim($event->field_signup_limit[LANGUAGE_NONE][0]['value']);

    // If there is a limit
    if (($limit != "") and (intval($limit) >= 0)) {

      // Check registered more than limit
      if ($flag_register->get_count($nid) >= $limit) {

        // If not registered, show waitlist
        if (!$flag_register->is_flagged($nid, $account->uid)) {
          if ($is_past_event) {
            return 'show_closed';
          }
          return 'show_waitlist';
        }

      }
    }
  }

  // Check payments
  if (module_exists("tm_payments")) {
    if (_tm_payments_is_payment_enabled($event)) {

      // check not already registered
      if (!tm_events_user_is_registered($event->nid, $account->uid)) {

        // if past event, check if field_event_payment_post_event enabled
        if (_tm_event_is_past($event)) {
          if (isset($event->field_event_payment_post_event[LANGUAGE_NONE][0]['value'])) {
            $payment_post_event = $event->field_event_payment_post_event[LANGUAGE_NONE][0]['value'];
          
            if ($payment_post_event) {
              return 'show_checkout';
            }
          }
        } else {
          // not a past event, show checkout
          return 'show_checkout';
        }
      }
    }
  }

  // Check if the event has already happened
  if ($is_past_event) {
    return 'show_closed';
  }

  // Can register
  return "show_register";

}

/** 
 * Helper method to determine if event has happened
 */
function _tm_event_is_past($event) {

  // Check if the event has already happened
  if (isset($event->field_event_date[LANGUAGE_NONE][0]['value2'])) {
    
    $timezone = _tm_get_event_timezone($event);
    $event_date = new DateTime($event->field_event_date[LANGUAGE_NONE][0]['value2'], new DateTimeZone($timezone));

    $now = new DateTime('now', new DateTimeZone($timezone));

    // past event
    if ($event_date < $now) {
      return true;
    }
  }

  return false;
}
