<?php
/**
 * @file
 * Code for the TM Events feature.
 * 
 * @author Ian C (ian@travelmassive.com)
 */

include_once 'tm_events.features.inc';
include_once 'tm_events.communication.inc';
include_once 'tm_events.helpers.inc';
include_once 'tm_events.registration.inc';
include_once 'tm_events.csv.inc';
include_once 'tm_events.token.inc';
include_once 'tm_events.contact.inc';
include_once 'tm_events.display.inc';
include_once 'tm_events.permissions.inc';
include_once 'tm_events.edit.inc';
include_once 'tm_events.flags.inc';
include_once 'tm_events.ical.inc';

/*
* Implements hook_menu()
*/
function tm_events_menu() {
  // need to change the permissions on both of these 
  // to be chapter leaders of the referenced event
  $items['events/send-announcement/%node'] = array(
    'title' => t('Send Announcement'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tm_events_communication_form'),
    'access callback' => 'tm_events_check_announcement_callback',
    'attributes' => array('class' => 'classname'),
    'type' => MENU_CALLBACK,
  );
  $items['events/manage-registrations/%node'] = array(
    'title' => t('Manage registrations'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tm_events_manage_registrations_form'),
    'access callback' => 'tm_events_check_permission_callback',
    'type' => MENU_CALLBACK,
  );
  $items['events/download-csv/%'] = array(
    'title' => t('Download RSVPs'),
    'page callback' => 'tm_events_download_csv',
    'page arguments' => array(2),
    'access callback' => 'tm_events_download_csv_check',
    'type' => MENU_CALLBACK,
  );
  $items['events/send-announcement-test/%node'] = array(
    'title' => t('Send test email'),
    'page callback' => 'tm_events_test_email_ajax',
    'access callback' => 'tm_events_check_announcement_callback',
    'type' => MENU_CALLBACK,
  );
  $items['events/send-announcement-callback/%node'] = array(
    'title' => t('Send event emails'),
    'page callback' => 'tm_events_send_emails_ajax',
    'access callback' => 'tm_events_check_announcement_callback',
    'type' => MENU_CALLBACK,
  );
  $items['events/message/%node'] = array(
    'title' => t('Message event organizers'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tm_events_contact_form',1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['node/new/event'] = array(
    'title' => t('New event'),
    'page callback' => 'tm_events_new_event',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['events/download-ical/%'] = array(
    'title' => t('Download iCal'),
    'page callback' => 'tm_events_download_ical',
    'page arguments' => array(2),
    'access callback' => 'tm_events_download_ical_check',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implement hook_ds_field_info()
 */
// see: https://ohthehugemanatee.org/blog/2014/04/02/how-to-create-a-custom-display-suite-field/
function tm_events_ds_fields_info($entity_type) {
  if ($entity_type != 'node') {
    return;
  }
  $fields = array();

  $fields['tm_ds_next_event'] = array(
    'title' => t('Next event'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('chapter|*'),
    'function' => '_tm_next_event'
  );

  $fields['tm_ds_date_avatar'] = array(
    'title' => t('Date avatar'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('event|*',),
    'function' => '_tm_date_avatar'
  );

  $fields['tm_ds_fulldate_event'] = array(
    'title' => t('Full datetime event'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('event|full',),
    'function' => '_tm_fulldate_event'
  );

  $fields['tm_ds_event_message'] = array(
    'title' => t('Event message'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('event|full',),
    'function' => '_tm_event_message'
  );

  $fields['tm_ds_event_location'] = array(
    'title' => t('Event location'),
    'field_type' => DS_FIELD_TYPE_FUNCTION,
    'ui_limit' => array('event|full',),
    'function' => '_tm_event_location'
  );

  return array($entity_type => $fields);
}

/**
 * Implement hook_theme()
 */
function tm_events_theme() {
  return array(
    'tm_date_avatar' => array(
      'variables' => array(
        'date' => NULL
      ),
      'path' => drupal_get_path('module','tm_events') . '/templates/fields',
      'template' => 'tm_date_avatar'
    )
  );
}

/* 
 * Hook - Add sort toggles to events page
 */
function tm_events_page_alter(&$page) {

  // Split url parts
  $url_parts = explode("/", request_path());

  // catch either:
  // /events
  // /events/list/conferences
  if (($url_parts[0] == "events") and ((sizeof($url_parts) == 1) or (sizeof($url_parts) == 3))) {

    // only show for /events/list/etc
    if ((sizeof($url_parts) == 3) and ($url_parts[1] != "list")) {
      return;
    }

    $event_types = array();
    $default_event_type = "";

    global $conf;
    if (!isset($conf["tm_event_types"])) { return; }
    if (!isset($conf["tm_event_types_display"])) { return; }
    if (!isset($conf["tm_event_types_default"])) { return; }

    // get event types from config
    $event_types = $conf["tm_event_types"];
    $tm_event_types_display = $conf["tm_event_types_display"];
    $default_event_type = $conf["tm_event_types_default"];
    
    $url_event_type = $default_event_type; // default list method
    if (sizeof($url_parts) == 3) {
      $url_event_type = $url_parts[2]; // ie: title for /events/list/conferences
    }
   
    // create buttons
    $html = '<ul class="tabs-primary tabs primary">';
    foreach ($tm_event_types_display as $event_type => $name) {

      $css_classes = "";
      if ($url_event_type == $event_type) { 
        $css_classes = "is-active active";
      }

      $url_arg = "";
      if ($event_type != $default_event_type) {
        $url_arg = "/list/" . $event_type;
      }

      $html .= '<li class="tabs-primary__tab ' . $css_classes . '">
        <a href="/events' . $url_arg . '" class="tabs-primary__tab-link '.$css_classes.'">' . $name . '</a>
      </li>';
    }
    $html .= '</ul>';

    // add html to page header
    $page['header'] = array('#markup' => $html);

  }
}

/*
 * Hook - Update title of events page
 */
function tm_events_views_post_execute(&$view) {
 
  // make sure we are on events page
  if ($view->name == 'events') {

    // Split url parts
    $url_parts = explode("/", request_path());

    // catch either:
    // /events
    // /events/list/conferences
    if (($url_parts[0] == "events") and (sizeof($url_parts) == 3)) {

      global $conf;
      // get event types from config
      if (!isset($conf["tm_event_types_display"])) { return; }
      $tm_event_types_display = $conf["tm_event_types_display"];

      // Step 1. Change Title
      // if we match event type, change the page title
      $url_event_type = $url_parts[2];
      if (array_key_exists($url_event_type, $tm_event_types_display)) {
        $view->build_info['title'] = $tm_event_types_display[$url_event_type];
      }

      // Step 2. Show Event Tip
      if (isset($conf['tm_event_types_tips'][$url_event_type])) {
        $tip = $conf['tm_event_types_tips'][$url_event_type];
        drupal_set_message($tip, 'page_notice');
      }
    }
  }
}

/**
 * Hook - Set default images
 * Refer to settings.php configuration
 */
function tm_events_preprocess_field(&$variables) {

  global $conf;

  // Check element type
  $element_type = null;
  if (isset($variables['element']['#object']->type)) {
    $element_type = $variables['element']['#object']->type;
  }

  // Only operate on event
  if ($element_type != "event") {
    return;
  }

  // Replace default cover image
  if ($variables['element']['#field_name'] == 'field_image') {
    $variables['items'][0]['#item']['uri'] = _tm_events_get_default_image($variables['items'][0]['#item']['uri'], $variables['element']['#object']->nid);
  }

}

/** 
 * Hook - Alter event node
 * Hide organizers if field_event_hide_organizers set
 */
function tm_events_node_view($node, $view_mode, $langcode) {

  global $user;

  // Check event
  if ($node->type != 'event') {
    return;
  }

  if ($view_mode == 'full') {

    // hide organizers
    if (isset($node->field_event_hide_organizers[LANGUAGE_NONE][0])) {
      if ($node->field_event_hide_organizers[LANGUAGE_NONE][0]['value']) {

        // http://timonweb.com/posts/programmatically-hiding-a-fieldgroup-on-a-node-display-in-drupal-7/
        $node->content['#groups']['group_organizers_wrapper']->format_type = 'hidden';
        hide($node->content['field_organizer']);  
      }
    }

    // preview mode
    if (tm_events_is_preview_mode($node->nid)) {
        drupal_set_message("This event is in Preview mode. Only people with the link can see this event.", "help-tip");
    }

    // if event has chapter, drop cookie to set default chapter on signup page
    if (isset($node->field_chapter[LANGUAGE_NONE][0]['target_id'])) {
      $chapter_id = $node->field_chapter[LANGUAGE_NONE][0]['target_id'];
      user_cookie_save(array('chapter_referral_id'=>$chapter_id));
    }

    // show reminder to send announcement
    // exclude external rsvp events
    if (tm_events_check_permission_edit_event($user, $node)) {
      tm_events_show_announcement_tip($node);
    }

  }
}
