<?php
/**
 * @file
 * Code for the TM Commissions feature.
 */

include_once 'tm_commissions.reports.inc';
include_once 'tm_commissions.summary.inc';


function tm_commissions_menu() {

	global $conf;

	$items = array();

  $items['chapters/%/commissions'] = array(
    'title' => 'Chapter Commissions',
    'page callback' => 'tm_commissions_reports_chapter_commissions_confirm',
    'page arguments' => array(1),
    'access callback' => array('tm_commissions_access_commissions_check'),
    'type' => MENU_CALLBACK,
  );

  $items['chapters/%/commissions/%'] = array(
    'title' => 'Chapter Commissions',
    'page callback' => 'tm_commissions_reports_chapter_commissions',
    'page arguments' => array(1),
    'access callback' => array('tm_commissions_access_commissions_check'),
    'type' => MENU_CALLBACK,
  );

  $items['chapters/all-chapters/commissions'] = array(
    'title' => 'Commissions Report',
    'page callback' => 'tm_commissions_reports_all_chapter_commissions_confirm',
    'page arguments' => array(3),
    'access callback' => array('tm_commissions_access_commissions_check'),
    'type' => MENU_CALLBACK,
  );

  $items['chapters/all-chapters/commissions/%'] = array(
    'title' => 'Commissions Report',
    'page callback' => 'tm_commissions_reports_all_chapter_commissions',
    'page arguments' => array(3),
    'access callback' => array('tm_commissions_access_commissions_check'),
    'type' => MENU_CALLBACK,
  );

  $items['chapters/all-chapters/commissions-by-region/%'] = array(
    'title' => 'Region Commissions',
    'page callback' => 'tm_commissions_reports_region_commissions_confirm',
    'page arguments' => array(3),
    'access callback' => array('tm_commissions_access_region_commissions_check'),
    'type' => MENU_CALLBACK,
  );

  $items['chapters/all-chapters/commissions-by-region/%/%'] = array(
    'title' => 'Region Commissions',
    'page callback' => 'tm_commissions_reports_region_commissions',
    'page arguments' => array(3,4),
    'access callback' => array('tm_commissions_access_region_commissions_check'),
    'type' => MENU_CALLBACK,
  );

	return $items;
}

/**
 * Permission callback. Check if user can access commissions data of chapter
 */
function tm_commissions_access_commissions_check() {

  global $user;

  // require signed in user
  if (!user_is_logged_in()) {
    return;
  }

  // get account
  $account = user_load($user->uid);
  $nid = _orig_nid();

  // is chapter leader of chapter, moderator or admin
  if ($nid != null) {
    if (tm_users_is_chapter_leader($account->uid, $nid)) {
      return true;
    }
  }

  // allow moderator and admin
  if ((in_array("moderator", $account->roles)) or (in_array("administrator", $account->roles))) {
    return true;
  }

  // allow chapter leader to access all chapters reports
  if (arg(1) == "all-chapters") {
    if (in_array("chapter leader", $account->roles)) {
      return true;
    }
  }

  // not allowed
  return false;
}

/**
 * Permission callback. Check if a user can access commissions report
 */
function tm_commissions_access_region_commissions_check() {
  
  global $conf;
  global $user;

  // require signed in user
  if (!user_is_logged_in()) {
    return;
  }

  // get account
  $account = user_load($user->uid);

  // allow moderator and admin
  if ((in_array("moderator", $account->roles)) or (in_array("administrator", $account->roles))) {
    return true;
  }

  // check if have permission
  if (in_array($user->uid, $conf["tm_commissions_users_who_can_access_region_reports"])) {
    return true;
  }

  return false;
}

?>