<?php

function tm_notifications_event_signup_tm_notif_info() {
  $notification = array();
  $notification['user_signup_event'] = array(
    'title' => 'User signed up to event',
    'description' => 'User signed up to event',
    //'subject' => array(
    //  'title' => 'Subject',
    //  'description' => 'description',
    //),
    //'body' => array(
    //  'title' => 'body',
    //  'description' => 'description',
    //),
    'tokens' => array(
      // The token types that have specific context. Can be multiple token types like 'term' and/or 'user'
      'token_types' => array('node', 'current-user'),
      // A boolean TRUE or FALSE whether to include 'global' context tokens like [current-user:*] or [site:*]. Defaults to TRUE.
      'global_types' => FALSE,
      // A boolean whether to include the 'Click this token to insert in into the the focused textfield' JavaScript functionality. Defaults to TRUE.
      'click_insert' => TRUE
    )
  );
  
  return $notification;
}

function tm_notifications_flag_flag($flag, $entity_id, $account, $flagging) {
  // We want to target the signup flag on nodes.
  if ($flag->name == 'signup' && $flag->entity_type == 'node') {
    $node = node_load($entity_id);
    // Only for event nodes.
    if ($node->type == 'event') {
      tm_notifications_notify('user_signup_event', $account, array('node' => $node));
    }
  }
}