<?php
/**
 * @file
 * Code for the TM Notifications Event feature.
 */

include_once 'tm_notifications_event.features.inc';

/**
 * Implements hook_tm_notif_info()
 */
function tm_notifications_event_tm_notif_info() {
  $notification = array();
  $notification['user_event_register'] = array(
    'title' => 'Member registered for event',    
    'description' => 'Send the member a confirmation when registering for an event.',
    'use_cron' => FALSE,
    'tokens' => array(
      // The token types that have specific context. Can be multiple token types like 'term' and/or 'user'
      'token_types' => array('node', 'current-user'),
      // A boolean TRUE or FALSE whether to include 'global' context tokens like [current-user:*] or [site:*]. Defaults to TRUE.
      'global_types' => FALSE,
      // A boolean whether to include the 'Click this token to insert in into the the focused textfield' JavaScript functionality. Defaults to TRUE.
      'click_insert' => TRUE
    )
  );
  
  $notification['user_event_unregister'] = array(
    'title' => 'Member unregistered from event',
    'description' => 'Send the member a confirmation when unregistering for an event.',
    'use_cron' => FALSE,
    'tokens' => array(
      // The token types that have specific context. Can be multiple token types like 'term' and/or 'user'
      'token_types' => array('node', 'current-user'),
      // A boolean TRUE or FALSE whether to include 'global' context tokens like [current-user:*] or [site:*]. Defaults to TRUE.
      'global_types' => FALSE,
      // A boolean whether to include the 'Click this token to insert in into the the focused textfield' JavaScript functionality. Defaults to TRUE.
      'click_insert' => TRUE
    )
  );

  $notification['user_event_join_waitlist'] = array(
    'title' => 'Member joined waitlist for event',    
    'description' => 'Send the member a confirmation when joining waiting list.',
    'use_cron' => FALSE,
    'tokens' => array(
      // The token types that have specific context. Can be multiple token types like 'term' and/or 'user'
      'token_types' => array('node', 'current-user'),
      // A boolean TRUE or FALSE whether to include 'global' context tokens like [current-user:*] or [site:*]. Defaults to TRUE.
      'global_types' => FALSE,
      // A boolean whether to include the 'Click this token to insert in into the the focused textfield' JavaScript functionality. Defaults to TRUE.
      'click_insert' => TRUE
    )
  );
  
  $notification['event_added_member_chapter'] = array(
    'title' => 'Event added to city',
    'description' => 'Send a notification to all the members of a chapter when an event is added.',
    'use_cron' => TRUE,
    'tokens' => array(
      // The token types that have specific context. Can be multiple token types like 'term' and/or 'user'
      'token_types' => array('node', 'current-user'),
      // A boolean TRUE or FALSE whether to include 'global' context tokens like [current-user:*] or [site:*]. Defaults to TRUE.
      'global_types' => FALSE,
      // A boolean whether to include the 'Click this token to insert in into the the focused textfield' JavaScript functionality. Defaults to TRUE.
      'click_insert' => TRUE
    )
  );
  
  return $notification;
}

/**
 * Implement hook_flag_flag()
 */
function tm_notifications_event_flag_flag($flag, $entity_id, $account, $flagging) {
  // We want to target the register flag on nodes.
  if ($flag->name == 'event_register' && $flag->entity_type == 'node') {
    $node = node_load($entity_id);
    // Only for event nodes.
    if ($node->type == 'event') {
      tm_notifications_notify('user_event_register', $account, array('node' => $node));
    }
  }

  // We want to target the register flag on nodes.
  if ($flag->name == 'event_waitlist' && $flag->entity_type == 'node') {
    $node = node_load($entity_id);
    // Only for event nodes.
    if ($node->type == 'event') {
      tm_notifications_notify('user_event_join_waitlist', $account, array('node' => $node));
    }
  }
}

/**
 * Implement hook_flag_unflag()
 */
function tm_notifications_event_flag_unflag($flag, $entity_id, $account, $flagging) {
  // We want to target the unregister flag on nodes.
  if ($flag->name == 'event_register' && $flag->entity_type == 'node') {
    $node = node_load($entity_id);
    // Only for event nodes.
    if ($node->type == 'event') {
      tm_notifications_notify('user_event_unregister', $account, array('node' => $node));
    }
  }

  // Note: No notification if we leave the waiting list

}

/**
 * Implements hook_node_insert()
 */
function tm_notifications_event_node_insert($node) {
  if ($node->type == 'event') {
    $chapter_nid = $node->field_chapter[LANGUAGE_NONE][0]['target_id'];
    
    // Get all the users that flagged the chapter
    $chapter_members = flag_get_entity_flags('node', $chapter_nid, 'signup');
    
    foreach ($chapter_members as $member) {
      $account = user_load($member->uid);
      tm_notifications_notify('event_added_member_chapter', $account, array('node' => $node));
    }
  }
}
