<?php
/**
 * @file
 * Code for the TM Notifications Event feature.
 */

include_once 'tm_notifications_event.features.inc';

/**
 * Implements hook_tm_notif_info()
 */
function tm_notifications_event_tm_notif_info() {
  $notification = array();
  $notification['user_event_join'] = array(
    'title' => 'Member joined event',    
    'description' => 'Send the member a confirmation when joining an event.',
    'use_cron' => FALSE,
    'tokens' => array(
      // The token types that have specific context. Can be multiple token types like 'term' and/or 'user'
      'token_types' => array('node', 'current-user'),
      // A boolean TRUE or FALSE whether to include 'global' context tokens like [current-user:*] or [site:*]. Defaults to TRUE.
      'global_types' => FALSE,
      // A boolean whether to include the 'Click this token to insert in into the the focused textfield' JavaScript functionality. Defaults to TRUE.
      'click_insert' => TRUE
    )
  );
  
  $notification['user_event_unjoin'] = array(
    'title' => 'Member unjoined event',
    'description' => 'Send the member a confirmation when unjoining an event.',
    'use_cron' => FALSE,
    'tokens' => array(
      // The token types that have specific context. Can be multiple token types like 'term' and/or 'user'
      'token_types' => array('node', 'current-user'),
      // A boolean TRUE or FALSE whether to include 'global' context tokens like [current-user:*] or [site:*]. Defaults to TRUE.
      'global_types' => FALSE,
      // A boolean whether to include the 'Click this token to insert in into the the focused textfield' JavaScript functionality. Defaults to TRUE.
      'click_insert' => TRUE
    )
  );
  
  $notification['event_added_member_chapter'] = array(
    'title' => 'Event added to city',
    'description' => 'Send a notification to all the members of a chapter when an event is added.',
    'use_cron' => TRUE,
    'tokens' => array(
      // The token types that have specific context. Can be multiple token types like 'term' and/or 'user'
      'token_types' => array('node', 'current-user'),
      // A boolean TRUE or FALSE whether to include 'global' context tokens like [current-user:*] or [site:*]. Defaults to TRUE.
      'global_types' => FALSE,
      // A boolean whether to include the 'Click this token to insert in into the the focused textfield' JavaScript functionality. Defaults to TRUE.
      'click_insert' => TRUE
    )
  );
  
  return $notification;
}

/**
 * Implement hook_flag_flag()
 */
function tm_notifications_event_flag_flag($flag, $entity_id, $account, $flagging) {
  // We want to target the signup flag on nodes.
  if ($flag->name == 'signup' && $flag->entity_type == 'node') {
    $node = node_load($entity_id);
    // Only for event nodes.
    if ($node->type == 'event') {
      tm_notifications_notify('user_event_join', $account, array('node' => $node));
    }
  }
}

/**
 * Implement hook_flag_unflag()
 */
function tm_notifications_event_flag_unflag($flag, $entity_id, $account, $flagging) {
  // We want to target the signup flag on nodes.
  if ($flag->name == 'signup' && $flag->entity_type == 'node') {
    $node = node_load($entity_id);
    // Only for event nodes.
    if ($node->type == 'event') {
      tm_notifications_notify('user_event_unjoin', $account, array('node' => $node));
    }
  }
}

/**
 * Implements hook_node_insert()
 */
function tm_notifications_event_node_insert($node) {
  if ($node->type == 'event') {
    $chapter_nid = $node->field_chapter[LANGUAGE_NONE][0]['target_id'];
    
    // Get all the users that flagged the chapter
    $chapter_members = flag_get_entity_flags('node', $chapter_nid, 'signup');
    
    foreach ($chapter_members as $member) {
      $account = user_load($member->uid);
      tm_notifications_notify('event_added_member_chapter', $account, array('node' => $node));
    }
  }
}
