<?php

function orchid_menu() {
  $items = array();
  $items['orchid/jsconnect'] = array(
    'title' => 'JSConnect ping', 
    'description' => 'Provides user information to vanilla jsconnect', 
    'page callback' => 'orchid_jsconnect_auth', 
    'access callback' => TRUE, 
    'type' =>  MENU_CALLBACK,
  ); 
  $items['admin/config/vanilla'] = array(
    'title' => 'Vanilla Forum settings',
    'description' => 'Vanilla forum settings.',
    'position' => 'right',
    'weight' => -15,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/vanilla/orchid'] = array(
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('orchid_settings'),
    'title' => 'Vanilla forum settings',
    'description' => 'Configure the settings for your Vanilla forum.',
  );
  return $items;
}
/**
 * Implementation of hook_perm().
 */
function orchid_perm() {
  return array('access vanilla forum');
}

/**
 * Implementation of hook_block_info().
 */
function orchid_block_info($op = 'list', $delta = 'all_level', $edit = array()) {
       $blocks = array();
       $blocks['embvan'] = array(
                'info' => t('vanilla forum embed'),                     
       );
       return $blocks;
}
function orchid_block_view($delta = ''){
      $block['subject'] = '';
      $block['content'] = theme('embed_vanilla');
      return $block;
}

/**
 * Implementation of hook_theme().
 */
function orchid_theme() {
  $items['embed_vanilla'] = array(
         'variables'=> array()); 
  return $items;
}

/**
 * admin settings form functions
 */
function orchid_settings() {

  $form = array();
  $form['vanilla-settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Vanilla settings'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['vanilla-settings']['orchid_vanilla_clientid'] = array(
    '#type' => 'textfield',
    '#title' => t('Client id'),
    '#default_value' =>  variable_get('orchid_vanilla_clientid','1234'),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('<p>The jsconnect client id of your Drupal cms in the Vanilla dashboard.</p>'),
    '#required' => TRUE,
  );
  $form['vanilla-settings']['orchid_vanilla_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('Shared secret'),
    '#default_value' =>  variable_get('orchid_vanilla_secret','1234'),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('<p>The JSConnect shared secret between your Drupal CMS and your Vanilla forum.</p>'),
    '#required' => TRUE,
  );
  $form['vanilla-settings']['orchid_vanilla_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Vanilla forum url'),
    '#default_value' =>  variable_get('orchid_vanilla_url',''),
    '#size' => 50,
    '#maxlength' => 100,
    '#description' => t('<p>Root URL of your Vanilla forum installation.</p>'),
    '#required' => TRUE,
  );
 //if (variable_get('user_pictures', 0)) {
    $form['vanilla-optionnal-settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('Optional settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['vanilla-optionnal-settings']['orchid_avatar_sync'] = array(
      '#type' => 'checkbox',
      '#title' => t('Synchronize avatar'),
      '#default_value' =>  variable_get('orchid_avatar_sync',''),
      '#description' => t('<p>Allow drupal to share avatar with vanilla.</p>'),
    );
    $form['vanilla-optionnal-settings']['orchid_avatar_style'] = array(
      '#type' => 'select',
      '#title' => t('Avatar size'),
      '#options' => image_style_options(),
      '#description' => t("<p>Choose a size which won't break layout with your vanilla theme.</p>"),
    );
  //}
  return system_settings_form($form);
}


/**
 * Provides jsconnect data
 */
function orchid_jsconnect_auth(){
  global $user;
  $user = user_load($user->uid); // load full user object
  $signedIn = (isset($user->uid) && ($user->uid > 0)) ? true : false; 
  $clientID = variable_get('orchid_vanilla_clientid','1234');
  $secret = variable_get('orchid_vanilla_secret','1234');
  $avatar_shared = variable_get('orchid_avatar_sync',false);
  $avatar_size = variable_get('orchid_avatar_style','thumbnail');
  $account = array();

  /*if (is_numeric($user->field_avatar)) {
        $user->picture = file_load($user->field_avatar);
  }*/
  // IC - use TM avatar
  if (isset($user->field_avatar[LANGUAGE_NONE][0]['uri'])) {
    $image_url = image_style_url("avatar", $user->field_avatar[LANGUAGE_NONE][0]['uri']);
  } else {
    $image_url = image_style_url("avatar", "public://default_images/avatar-default.png");
  }

  // only do SSO for approved users
  // this way we don't have to log out/in when user goes from unapproved -> approved
  if (($signedIn) and (in_array("approved user", $user->roles))) {
     $account['uniqueid'] = $user->uid;
     $account['name'] = $user->field_user_first_name[LANGUAGE_NONE][0]['value'] . " " . $user->field_user_last_name[LANGUAGE_NONE][0]['value'];
     $account['email'] =  $user->mail;
     if($avatar_shared) {
       $account['photourl'] = $image_url; //($user->picture && $user->picture->uri) ? file_create_url(image_style_path($avatar_size,$user->picture->uri)) : '';
     }

     // IC - add user roles
     $roles = array("member"); // member is default
     foreach ($user->roles as $rid => $rolename) {
      $roles[] = $rolename;
     }

     // IC - add nids of chapters joined
     $chapter_nids = tm_users_get_chapters($user);
     foreach ($chapter_nids as $chapter_nid) {
      $roles[] = "chapter-" . $chapter_nid;
     }

     // IC - add nids of chapters leading
     $chapter_leading_nids = tm_users_get_chapters_leading($user);
     foreach ($chapter_leading_nids as $chapter_nid) {
      $roles[] = "chapter-leader-" . $chapter_nid;
     }

     // set account roles
     $account['roles'] = implode(",", $roles); // ie: member,moderator,chapter leader;

     // IC - add extra fields
     $account['usermeta'] = array('drupal_uid' => $user->uid, 'drupal_profile_url' => drupal_get_path_alias("user/" . $user->uid));
  }  
  module_load_include('php', 'orchid', 'include/functions.jsconnect');
  $secure = true; // this should be true unless for testing modes.
  WriteJsConnect($account	, $_GET, $clientID, $secret, $secure);
  exit();
}


/**
 * hook_ctools_plugin_directory()
 */
function orchid_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * theme for key 'embed_vanilla'
 */ 

function theme_embed_vanilla(){
  $vanilla_root = variable_get('orchid_vanilla_url','');
  return '<script type="text/javascript" src="'.$vanilla_root.'/plugins/embedvanilla/remote.js"></script>';
}

/*
 * Signout from vanilla when user logs out
 * see: https://www.drupal.org/node/1691392
 */
function orchid_user_logout($account) {
  global $conf;
  $vanilla_cookies = array("Vanilla", "Vanilla-ConnectFlood", "Vanilla-Vv", "Vanilla-Volatile");
  foreach ($vanilla_cookies as $cookie_name) {
    unset($_COOKIE[$cookie_name]);
    setcookie($cookie_name, '', time() - 3600, "/");
  }
}
