<?php
/**
 * @file
 * Industry segments taxonomy terms to import on installation.
 */
$tm_segments_terms = array(
  'Online Travel Industry' => array(
    'Online Travel Agent (OTA)',
    'Meta-search (Airfare)',
    'Meta-search (Hotel)',
    'Meta-search (All travel)',
    'Travel Forum / Community',
    'Multi-modal travel search',
    'Hotel booking engine',
    'Last minute hotel booking',
    'Itinerary planning',
    'Vacation rental website',
    'Peer to Peer travel',
    'Travel Insurance',
    'Blog network',
    'Review website',
    'Affiliate network',
    'Tour booking',
    'Local tours',
    'Professional Consulting',
    'Innovation'
  ),
  'Blogger' => array(
    'Travel Blogger',
    'Adventure travel blogging',
    'Family travel blogging',
    'Food blogging',
    'Travel Tips / Information',
    'Vlogger',
    'Womens Travel',
    'Fashion Travel',
    'Instagram / Photography',
  ),
  'Media' => array(
    'Media',
    'Media and Events',
    'Journalists',
    'Trade magazines',
    'Editorial offices',
    'TV/Radio-stations',
    'Publishers',
    'Travel photography',
    'Film Maker',
  ),
  'Tourism Organization/Association' => array(
    'Organizations',
    'Associations',
    'Tourism Board',
    'Spas and health institutions',
  ),
  'Tour Operators/Travel Agencies' => array(
    'Tour Operator',
    'Travel Agencies',
    'Adventure Tours',
    'Tour Guide',
    'Cultural & Study Tours',
    'Incentive Holidays',
    'Incoming Agencies',
    'Young Travel 18-35',
    'Journeys for children and teenagers',
    'Cruises',
    'Safari Holidays',
    'Language Holidays',
    'Town sightseeing tours',
    'Winter Sports',
    'Golf Holidays',
    'Wellness Trips',
    'Family Trips',
    'Luxury Travel',
  ),
  'Accommodation' => array(
    'Hotel Chains',
    'Boutique Hotel',
    'Hostels',
    'Resorts',
    'Holiday apartments',
    'Spa',
    'Hotel representatives',
    'Serviced apartment',
    'Hospitality',
  ),
  'Means of transport/carriers' => array(
    'Coach companies',
    'Airport',
    'Airlines',
    'Car rental companies',
    'Railway companies',
    'Shipping/ferry lines',
    'River Cruises',
    'Yacht Charter',
    'Limousine services',
    'Charter operators/Aviation Service',
  ),
  'Business Travel' => array(
    'Corporate Travel',
    'Business Travel Agencies',
    'Exhibition Centres',
    'Conference & Meeting Venue',
    'Fair organisers',
    'Incentive Travel',
    'Professional Conference Organisers',
    'Destination Management Companies',
  ),
  'IT and Software' => array(
    'Consulting Services',
    'IT and Software',
    'Reservation and booking technologies',
    'Distribution technologies',
    'CRM technologies',
    'Content management solutions',
    'Online Payment Systems',
    'Telecommunication',
  ),
  'Marketing' => array(
    'Brand Manager',
    'Marketing Manager',
    'Affiliate Marketing',
    'Customer Relationship',
    'Market Research',
    'Advertisting Agency',
    'Digital Marketing'
   ),
  'Information and Advice' => array(
    'Information and advice',
    'Education and further education',
    'Trade associations/organizations',
    'Press/ PR Agencies',
  ),
   'Investment' => array(
    'Angel Investor',
    'Venture Capital',
    'Mergers and Acquisitions',
    'Professional Services',
    'Startup Accelerator',
    'Startup Lab',
    'Investment Advisory',
  ),
  'Destination' => array(
    'Theme park',
    'National park',
    'Museum',
    'Art Gallery',
    'Exhibition / Show',
    'Tourist attraction',
  ),
  'Professional Education and Research' => array(
    'University',
    'College / Institution',
    'Student',
    'Science and research',
  ),
  'Travel Insider' => array(
    'Pilot',
    'Travel King',
    'Travel Queen',
    'Travel Professor',
    'Travel Massive'.
   ),
);
?>