<?php 
$tm_segments_terms = array(
  'Online Travel Industry' => array(
    'Online Travel Agent (OTA)',
    'Meta-search (Airfare)',
    'Meta-search (Hotel)',
    'Meta-search (All travel)',
    'Travel Forum / Community',
    'Multi-modal travel search',
    'Hotel booking engine',
    'Last minute hotel booking',
    'Itinerary planning',
    'Vacation rental website',
    'Peer to Peer travel',
    'Travel Insurance',
    'Blog network',
    'Review website',
    'Affiliate network',
    'Tour booking',
    'Local tours',
  ),
  'Blogger' => array(
    'Adventure travel blogging',
    'Family travel blogging',
    'Food blogging',
    'Travel Tips / Information',
    'Vlogger',
    'Womens Travel',
    'Fashion Travel',
    'Instagram / Photography',
  ),
  'Media' => array(
    'Media',
    'Journalists',
    'Trade magazines',
    'Editorial offices',
    'TV/Radio-stations',
    'Publishers',
    'Travel photography',
  ),
  'Tourism Organization/Association' => array(
    'Organizations',
    'Associations',
    'Touristic Representations/Tourism Boards',
    'Spas and health institutions',
  ),
  'Tour Operators/Travel Agencies' => array(
    'Tour Operator',
    'Travel Agencies',
    'Adventure Tours',
    'Cultural & Study Tours',
    'Incentive Holidays',
    'Incoming Agencies',
    'Young Travel 18-35',
    'Journeys for children and teenagers',
    'Cruises',
    'Safari Holidays',
    'Language Holidays',
    'Town sightseeing tours',
    'Winter Sports',
    'Golf Holidays',
    'Wellness Trips',
    'Family Trips',
    'Luxury Travel',
  ),
  'Accommodation' => array(
    'Hotel Chains',
    'Boutique Hotel',
    'Hostels',
    'Resorts',
    'Holiday apartments',
    'Spa',
    'Hotel representatives',
    'Serviced apartment',
    'Hospitality',
  ),
  'Means of transport/carriers' => array(
    'Coach companies',
    'Airport',
    'Airlines',
    'Car rental companies',
    'Railway companies',
    'Shipping/ferry lines',
    'River Cruises',
    'Yacht Charter',
    'Limousine services',
    'Charter operators/Aviation Service',
  ),
  'Business Travel' => array(
    'Travel Management Companies',
    'Business Travel Agencies',
    'Exhibition Centres',
    'Conference & Meeting Venue',
    'Fair organisers',
    'Incentive Travel',
    'Professional Conference Organisers',
    'Destination Management Companies',
  ),
  'IT and Software' => array(
    'IT and Software',
    'Reservation and booking technologies',
    'Distribution technologies',
    'CRM technologies',
    'Content management solutions',
    'Online Payment Systems',
    'Telecommunication',
  ),
  'Information and advice' => array(
    'Information and advice',
    'Education and further education',
    'Investment Services',
    'Trade associations/organizations',
    'Press/ PR Agencies',
  ),
  'Destination' => array(
    'Theme park',
    'National park',
    'Museum',
    'Exhibition / Show',
    'Tourist attraction',
  ),
  'Professional Education and Research' => array(
    'University',
    'College / Institution',
    'Student',
    'Science and research',
  ),
);
?>